### ISSUE TITLE
S3ObjectControlManagerTest.testDeleteTooManyOneReques failed sometimes

### ISSUE THREAD

**Issue by Chillax-0v0** [AutoMQ/automq-for-kafka#396]
https://github.com/AutoMQ/kafka-on-s3/actions/runs/6676151986/job/18144920779

```
> Task :metadata:S3UnitTest FAILED
org.apache.kafka.controller.S3ObjectControlManagerTest.testDeleteTooManyOneRequest() failed, log available in /home/runner/work/kafka-on-s3/kafka-on-s3/metadata/build/reports/testOutput/org.apache.kafka.controller.S3ObjectControlManagerTest.testDeleteTooManyOneRequest().test.stdout

Gradle Test Run :metadata:S3UnitTest > Gradle Test Executor 4 > S3ObjectControlManagerTest > testDeleteTooManyOneRequest() FAILED
    org.opentest4j.AssertionFailedError: expected: <0> but was: <1>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:1[97](https://github.com/AutoMQ/kafka-on-s3/actions/runs/6676151986/job/18144920779#step:5:98))
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:527)
        at app//org.apache.kafka.controller.S3ObjectControlManagerTest.testDeleteTooManyOneRequest(S3ObjectControlManagerTest.java:264)
```

**Comment by superhx** [comment]
Cannot reproduce anymore
