### ISSUE TITLE
amq-serverless attach need deattach first or this is AWS meta delay update bug?

### ISSUE THREAD

**Issue by superhx** [AutoMQ/automq-for-kafka#484]
```
[2023-11-28 09:01:00,818] INFO scan new failed node FailedNode{nodeId=3, volumeId='vol-0c5891e7180fd8c5e'} (org.apache.kafka.controller.stream.FailoverControlManager)
[2023-11-28 09:01:01,353] ERROR attach failed node 3 to target node 0 failed (org.apache.kafka.controller.stream.FailoverControlManager)
java.util.concurrent.CompletionException: java.util.concurrent.ExecutionException: Run [/opt/automq/scripts/amq-serverless, volume, attach, -v, vol-0c5891e7180fd8c5e, -n, 0], code:1  failed: failed to attach volume, err is failed to attach volume vol-0c5891e7180fd8c5e, err is failed to attach volume: VolumeInUse: vol-0c5891e7180fd8c5e is already attached to an instance
	status code: 400, request id: 2d438167-0ec0-468b-822b-8284d51aa510
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at org.apache.kafka.controller.stream.FailoverControlManager.lambda$attach$3(FailoverControlManager.java:239)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.util.concurrent.ExecutionException: Run [/opt/automq/scripts/amq-serverless, volume, attach, -v, vol-0c5891e7180fd8c5e, -n, 0], code:1  failed: failed to attach volume, err is failed to attach volume vol-0c5891e7180fd8c5e, err is failed to attach volume: VolumeInUse: vol-0c5891e7180fd8c5e is already attached to an instance
	status code: 400, request id: 2d438167-0ec0-468b-822b-8284d51aa510
	at com.automq.stream.s3.failover.DefaultServerless.check(DefaultServerless.java:72)
	at com.automq.stream.s3.failover.DefaultServerless.attach(DefaultServerless.java:38)
	at org.apache.kafka.controller.stream.FailoverControlManager.lambda$attach$3(FailoverControlManager.java:237)
	... 5 more
[2023-11-28 09:01:01,374] INFO attach failed node 3 to target node 4 success (org.apache.kafka.controller.stream.FailoverControlManager)
```

**Comment by superhx** [comment]
```
[2023-11-29 03:10:39,831] ERROR run failover task failed (org.apache.kafka.controller.stream.FailoverControlManager)
java.util.concurrent.ExecutionException: json parse ({"level":"info","ts":"2023-11-29T03:10:39.827Z","msg":"Add tag to volume vol-09f25b6a3cdc48533 success...  "}
[{"volumeId":"vol-09f25b6a3cdc48533","volumeType":"gp3","firstBindNodeId":"3"}]) fail
	at com.automq.stream.s3.failover.DefaultServerless.jsonParse(DefaultServerless.java:81)
	at com.automq.stream.s3.failover.DefaultServerless.scan(DefaultServerless.java:61)
	at org.apache.kafka.controller.stream.FailoverControlManager.scanFailedNodes(FailoverControlManager.java:99)
	at org.apache.kafka.controller.stream.FailoverControlManager.runFailoverTask(FailoverControlManager.java:90)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `[Lcom.automq.stream.s3.failover.DefaultServerless$QueryFailedNode;` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1767)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1541)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1488)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.handleNonArray(ObjectArrayDeserializer.java:345)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:197)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4899)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3846)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3814)
	at com.automq.stream.s3.failover.DefaultServerless.jsonParse(DefaultServerless.java:79)
	... 9 more
[2023-11-29 03:10:40,935] INFO scan new failed node FailedNode{nodeId=3, volumeId='vol-09f25b6a3cdc48533'} (org.apache.kafka.controller.stream.FailoverControlManager)
[2023-11-29 03:10:41,082] ERROR attach failed node 3 to target node 0 failed (org.apache.kafka.controller.stream.FailoverControlManager)
java.util.concurrent.CompletionException: java.util.concurrent.ExecutionException: Run [/opt/automq/scripts/amq-serverless, volume, attach, -v, vol-09f25b6a3cdc48533, -n, 0], code:1  failed: failed to attach volume, err is failed to attach volume vol-09f25b6a3cdc48533, err is expected exactly one instance, found: 1
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at org.apache.kafka.controller.stream.FailoverControlManager.lambda$attach$3(FailoverControlManager.java:244)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.util.concurrent.ExecutionException: Run [/opt/automq/scripts/amq-serverless, volume, attach, -v, vol-09f25b6a3cdc48533, -n, 0], code:1  failed: failed to attach volume, err is failed to attach volume vol-09f25b6a3cdc48533, err is expected exactly one instance, found: 1
	at com.automq.stream.s3.failover.DefaultServerless.check(DefaultServerless.java:72)
	at com.automq.stream.s3.failover.DefaultServerless.attach(DefaultServerless.java:38)
	at org.apache.kafka.controller.stream.FailoverControlManager.lambda$attach$3(FailoverControlManager.java:242)
	... 5 more
```
