### ISSUE TITLE
AutoMQ Kafka throw 'No space left on device' when receive heavy netowork traffic and can't recovery from this situation 

### ISSUE THREAD

**Issue by KaimingWan** [AutoMQ/automq-for-kafka#488]
## How to reproduce:
1. use AutoMQ Kafka installer to init a default cluster on AWS
2. create a r6i.4xlarge EC2 with AutoMQ Kafka AMI and execute the following command to write data
```
$KAFKA_HOME/kafka/bin/kafka-producer-perf-test.sh --topic test-topic --num-records=6553600 --throughput 1600 --record-size 458752 --producer-props bootstrap.servers=10.0.96.4:9092 > producer_1.log &
```
3.  Then we can see error in server.log and aws cloudwatch alarm alert can't be triggered.
```java

[2023-11-29 07:59:19,908] INFO [KafkaApi-1] produce cost (in microseconds), produce={count=10, max=1026.0, mean=460.6} callback={count=10, max=3.0002322E7, mean=3.00011152E7} ack={count=10, max=71.0, mean=27.1} (kafka.server.KafkaApis)
[2023-11-29 07:59:19,915] ERROR failed to write blocks, startOffset: 2220269568 (SlidingWindowService)
java.io.IOException: error writing file at offset 2220277760: No space left on device
	at com.automq.stream.thirdparty.moe.cnkirito.kdio.DirectIOLib.pwrite(DirectIOLib.java:298)
	at com.automq.stream.thirdparty.moe.cnkirito.kdio.DirectChannelImpl.write(DirectChannelImpl.java:77)
	at com.automq.stream.thirdparty.moe.cnkirito.kdio.DirectRandomAccessFile.write(DirectRandomAccessFile.java:65)
	at com.automq.stream.s3.wal.util.WALBlockDeviceChannel.write(WALBlockDeviceChannel.java:250)
	at com.automq.stream.s3.wal.util.WALBlockDeviceChannel.write(WALBlockDeviceChannel.java:218)
	at com.automq.stream.s3.wal.SlidingWindowService.writeBlockData(SlidingWindowService.java:338)
	at com.automq.stream.s3.wal.SlidingWindowService$WriteBlockProcessor.writeBlock(SlidingWindowService.java:533)
	at com.automq.stream.s3.wal.SlidingWindowService$WriteBlockProcessor.run(SlidingWindowService.java:527)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

4. Stop the write process and start a producer with light workload, the server still give the same error
```shell
$KAFKA_HOME/kafka/bin/kafka-producer-perf-test.sh --topic test-topic --num-records=6553600 --throughput 1600 --record-size 13107  --producer-props bootstrap.servers=10.0.96.4:9092
```
The kafka performance tool give the following logs:
```
[2023-11-29 07:59:19,917] WARN [Producer clientId=perf-producer-client] Got error produce response with correlation id 3353 on topic-partition test-topic-23, retrying (2147483646 attempts left). Error: NETWORK_EXCEPTION. Error Message: Disconnected from node 1 (org.apache.kafka.clients.producer.internals.Sender)
```

**Comment by Chillax-0v0** [comment]
![image](https://github.com/AutoMQ/automq-for-kafka/assets/78631860/87bb93cf-3390-40d9-994a-dd1d4a4240ff)
WAL capacity should not be greater than the real size of the block device.
