### ISSUE TITLE
broker give upload s3 error when receive burst network workload and the producer can't continue to write any data

### ISSUE THREAD

**Issue by KaimingWan** [AutoMQ/automq-for-kafka#501]
## How to produce
- Use AutoMQ Kafka Installer to install a default cluster with one broker on AWS
- prepare 2 r6i.4xlarge EC2 with AutoMQ Kafka AMI and start the following scripts to write data to topic. The topic have 128 partitions. Every EC2 execute the following 10 producers which means totaly 20 producers.

```shell

#!/bin/bash
#
#

# 设置要循环的次数
NUM_TIMES=10

for i in $(seq 1 $NUM_TIMES)
do
    $KAFKA_HOME/kafka/bin/kafka-producer-perf-test.sh \
    --topic test-topic \
    --num-records=6553600 \
    --throughput 5600  \
    --record-size 458752 \
    --producer-props bootstrap.servers=10.0.96.4:9092 >> producer.log &
done
```

- The producer log occuer exception
```java

[2023-12-01 03:27:55,745] WARN [Producer clientId=perf-producer-client] Bootstrap broker 10.0.96.4:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2023-12-01 03:28:03,040] WARN [Producer clientId=perf-producer-client] Bootstrap broker 10.0.96.4:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2023-12-01 03:28:04,488] WARN [Producer clientId=perf-producer-client] Bootstrap broker 10.0.96.4:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2023-12-01 03:28:06,380] WARN [Producer clientId=perf-producer-client] Bootstrap broker 10.0.96.4:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2023-12-01 03:28:10,145] WARN [Producer clientId=perf-producer-client] Bootstrap broker 10.0.96.4:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
```

- The controller server.log give exception
```java
[2023-12-01 03:22:15,463] WARN Retry task: kafka.log.stream.s3.network.ControllerRequestSender$RequestTask@5e29eeef, delay : 60000 ms (kafka.log.stream.s3.network.ControllerRequestSender)
[2023-12-01 03:22:21,031] INFO [Consumer clientId=AutoBalancerControllerConsumer-consumer-5778765974454381228, groupId=AutoBalancerControllerConsumerGroup-group-5778765974454381228] Disconnecting from node 12 due to socket connection setup timeout. The timeout value is 35859 ms. (org.apache.kafka.clients.NetworkClient)
[2023-12-01 03:22:21,477] INFO [Producer clientId=AutoBalancerMetricsReporterProducer] Disconnecting from node 12 due to socket connection setup timeout. The timeout value is 32830 ms. (org.apache.kafka.clients.NetworkClient)
[2023-12-01 03:22:28,782] INFO [AnomalyDetector id=0] Start detect (kafka.autobalancer.AnomalyDetector)
[2023-12-01 03:22:28,782] WARN Broker 0 metrics is out of sync, expected earliest time: 1701400928782, actual: 1701352286071 (kafka.autobalancer.model.BrokerUpdater)
[2023-12-01 03:22:28,782] INFO [AnomalyDetector id=0] Detect finished, next detect will be after 60000 ms (kafka.autobalancer.AnomalyDetector)
[2023-12-01 03:22:40,853] INFO [Producer clientId=AutoBalancerMetricsReporterProducer] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 25759 ms. (org.apache.kafka.clients.NetworkClient)
[2023-12-01 03:22:45,127] WARN UploadPartCopy for object c2a20000/_kafka_rZdE0DjZSrqy96PXrMUZVw/10796-1 fail, retry later (com.automq.stream.s3.operator.DefaultS3Operator)
java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.ApiCallAttemptTimeoutException: HTTP request execution did not complete before the specified timeout configuration: 30000 millis
	at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:65)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:79)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:103)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:184)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:159)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:79)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:103)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.core.internal.http.timers.AsyncTimeoutTask.run(AsyncTimeoutTask.java:52)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: software.amazon.awssdk.core.exception.ApiCallAttemptTimeoutException: HTTP request execution did not complete before the specified timeout configuration: 30000 millis
	at software.amazon.awssdk.core.exception.ApiCallAttemptTimeoutException$BuilderImpl.build(ApiCallAttemptTimeoutException.java:97)
	at software.amazon.awssdk.core.exception.ApiCallAttemptTimeoutException.create(ApiCallAttemptTimeoutException.java:38)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$setupAttemptTimer$8(MakeAsyncHttpRequestStage.java:228)
	... 7 more
```

## What I Expect
AutoMQ Kafka should receive the producer's data and metric alarm then can be triggered

**Comment by superhx** [comment]
Cannot reproduce. Previously, it was possibly due to a bug in cold data reading, which caused a failure in opening the partition and resulted in the inability to send.
