### ISSUE TITLE
LogClean load the first batch timestamp cause slow shutdown

### ISSUE THREAD

**Issue by superhx** [AutoMQ/automq-for-kafka#505]
```
"kafka-log-cleaner-thread-0" #128 prio=5 os_prio=0 cpu=20.21ms elapsed=161.76s tid=0x00007fd6a405ffe0 nid=0x3c9f waiting on condition  [0x00007fd6776f0000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.2/Native Method)
        - parking to wait for  <0x00000000f5337868> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(java.base@17.0.2/LockSupport.java:211)
        at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.2/CompletableFuture.java:1864)
        at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.2/ForkJoinPool.java:3463)
        at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.2/ForkJoinPool.java:3434)
        at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.2/CompletableFuture.java:1898)
        at java.util.concurrent.CompletableFuture.get(java.base@17.0.2/CompletableFuture.java:2072)
        at kafka.log.streamaspect.ElasticLogFileRecords$StreamSegmentInputStream.nextBatch(ElasticLogFileRecords.java:365)
        at org.apache.kafka.common.record.RecordBatchIterator.makeNext(RecordBatchIterator.java:37)
        at org.apache.kafka.common.record.RecordBatchIterator.makeNext(RecordBatchIterator.java:26)
        at org.apache.kafka.common.utils.AbstractIterator.maybeComputeNext(AbstractIterator.java:79)
        at org.apache.kafka.common.utils.AbstractIterator.hasNext(AbstractIterator.java:45)
        at kafka.log.streamaspect.ElasticLogSegment.loadFirstBatchTimestamp(ElasticLogSegment.scala:314)
        at kafka.log.streamaspect.ElasticLogSegment.getFirstBatchTimestamp(ElasticLogSegment.scala:329)
        at kafka.log.LogSegments$.$anonfun$getFirstBatchTimestampForSegments$1(LogSegments.scala:265)
        at kafka.log.LogSegments$.$anonfun$getFirstBatchTimestampForSegments$1$adapted(LogSegments.scala:264)
        at kafka.log.LogSegments$$$Lambda$2563/0x00000008014ef460.apply(Unknown Source)
        at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:100)
        at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:87)
        at scala.collection.convert.JavaCollectionWrappers$JCollectionWrapper.map(JavaCollectionWrappers.scala:72)
        at kafka.log.LogSegments$.getFirstBatchTimestampForSegments(LogSegments.scala:264)
        at kafka.log.UnifiedLog.getFirstBatchTimestampForSegments(UnifiedLog.scala:1774)
        at kafka.log.LogCleanerManager$.maxCompactionDelay(LogCleanerManager.scala:567)
        at kafka.log.LogCleanerManager.$anonfun$grabFilthiestCompactedLog$4(LogCleanerManager.scala:188)
        at kafka.log.LogCleanerManager$$Lambda$1583/0x00000008012c86a0.apply(Unknown Source)
        at scala.collection.immutable.List.map(List.scala:250)
        at scala.collection.immutable.List.map(List.scala:79)
        at kafka.log.LogCleanerManager.$anonfun$grabFilthiestCompactedLog$1(LogCleanerManager.scala:180)
        at kafka.log.LogCleanerManager.grabFilthiestCompactedLog(LogCleanerManager.scala:170)
        at kafka.log.LogCleaner$CleanerThread.cleanFilthiestLog(LogCleaner.scala:360)
        at kafka.log.LogCleaner$CleanerThread.tryCleanFilthiestLog(LogCleaner.scala:347)
        at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:334)
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)

"kafka-scheduler-6" #130 daemon prio=5 os_prio=0 cpu=35.85ms elapsed=161.76s tid=0x00007fd6a4065040 nid=0x3ca1 waiting on condition  [0x00007fd6774ef000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.2/Native Method)
        - parking to wait for  <0x00000000e5024f20> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(java.base@17.0.2/LockSupport.java:211)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.2/AbstractQueuedSynchronizer.java:715)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.2/AbstractQueuedSynchronizer.java:938)
        at java.util.concurrent.locks.ReentrantLock$Sync.lock(java.base@17.0.2/ReentrantLock.java:153)
        at java.util.concurrent.locks.ReentrantLock.lock(java.base@17.0.2/ReentrantLock.java:322)
        at kafka.log.LogCleanerManager.pauseCleaningForNonCompactedPartitions(LogCleanerManager.scala:223)
        at kafka.log.LogCleaner.pauseCleaningForNonCompactedPartitions(LogCleaner.scala:289)
        at kafka.log.LogManager.cleanupLogs(LogManager.scala:1341)
        at kafka.log.LogManager.$anonfun$startupWithConfigOverrides$2(LogManager.scala:599)
        at kafka.log.LogManager$$Lambda$1554/0x00000008012b9c60.apply$mcV$sp(Unknown Source)
        at kafka.utils.KafkaScheduler.$anonfun$schedule$2(KafkaScheduler.scala:116)
        at kafka.utils.KafkaScheduler$$Lambda$324/0x0000000800e279c0.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(java.base@17.0.2/Executors.java:539)
        at java.util.concurrent.FutureTask.runAndReset(java.base@17.0.2/FutureTask.java:305)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@17.0.2/ScheduledThreadPoolExecutor.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.2/ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.2/ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(java.base@17.0.2/Thread.java:833)
```

**Comment by superhx** [comment]
LogCleaner#abortCleaning will await the cleaning abort
```
"kafka-log-cleaner-thread-0" #153 prio=5 os_prio=0 cpu=370.32ms elapsed=336.52s tid=0x00007fb2c80a0480 nid=0x2f01 waiting on condition  [0x00007fb1b5bfd000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.2/Native Method)
        - parking to wait for  <0x00000000ff485868> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(java.base@17.0.2/LockSupport.java:211)
        at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.2/CompletableFuture.java:1864)
        at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.2/ForkJoinPool.java:3463)
        at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.2/ForkJoinPool.java:3434)
        at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.2/CompletableFuture.java:1898)
        at java.util.concurrent.CompletableFuture.get(java.base@17.0.2/CompletableFuture.java:2072)
        at kafka.log.streamaspect.ElasticLogFileRecords$StreamSegmentInputStream.nextBatch(ElasticLogFileRecords.java:366)
        at org.apache.kafka.common.record.RecordBatchIterator.makeNext(RecordBatchIterator.java:37)
        at org.apache.kafka.common.record.RecordBatchIterator.makeNext(RecordBatchIterator.java:26)
        at org.apache.kafka.common.utils.AbstractIterator.maybeComputeNext(AbstractIterator.java:79)
        at org.apache.kafka.common.utils.AbstractIterator.hasNext(AbstractIterator.java:45)
        at scala.collection.convert.JavaCollectionWrappers$JIteratorWrapper.hasNext(JavaCollectionWrappers.scala:41)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
        at kafka.log.Cleaner.cleanIntoV2(LogCleaner.scala:1118)
        at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:609)
        at kafka.log.Cleaner.$anonfun$doClean$6(LogCleaner.scala:548)
        at kafka.log.Cleaner.$anonfun$doClean$6$adapted(LogCleaner.scala:547)
        at kafka.log.Cleaner$$Lambda$2430/0x00000008014ae4f8.apply(Unknown Source)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at kafka.log.Cleaner.doClean(LogCleaner.scala:547)
        at kafka.log.Cleaner.clean(LogCleaner.scala:512)
        at kafka.log.LogCleaner$CleanerThread.cleanLog(LogCleaner.scala:396)
        at kafka.log.LogCleaner$CleanerThread.cleanFilthiestLog(LogCleaner.scala:368)
        at kafka.log.LogCleaner$CleanerThread.tryCleanFilthiestLog(LogCleaner.scala:347)
        at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:334)
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)

"partition_op_25" #252 daemon prio=5 os_prio=0 cpu=133.06ms elapsed=60.76s tid=0x00007fb2c80292f0 nid=0x2ff9 runnable  [0x00007fb1ae2af000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.2/Native Method)
        - parking to wait for  <0x00000000e52b53b0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.2/LockSupport.java:252)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@17.0.2/AbstractQueuedSynchronizer.java:1757)
        at kafka.log.LogCleanerManager.$anonfun$abortAndPauseCleaning$1(LogCleanerManager.scala:291)
        at kafka.log.LogCleanerManager.abortAndPauseCleaning(LogCleanerManager.scala:279)
        at kafka.log.LogCleanerManager.$anonfun$abortCleaning$1(LogCleanerManager.scala:261)
        at kafka.log.LogCleanerManager.abortCleaning(LogCleanerManager.scala:260)
        at kafka.log.LogCleaner.abortCleaning(LogCleaner.scala:214)
        at kafka.server.ReplicaManager.$anonfun$stopPartitions$1(ReplicaManager.scala:489)
        at kafka.server.ReplicaManager.$anonfun$stopPartitions$1$adapted(ReplicaManager.scala:480)
        at kafka.server.ReplicaManager$$Lambda$2504/0x00000008014e2000.apply(Unknown Source)
        at kafka.utils.Implicits$MapExtensionMethods$.$anonfun$forKeyValue$1(Implicits.scala:62)
        at kafka.server.ReplicaManager$$Lambda$2507/0x00000008014e36c0.apply(Unknown Source)
        at scala.collection.mutable.HashMap$Node.foreachEntry(HashMap.scala:633)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:499)
        at kafka.server.ReplicaManager.stopPartitions(ReplicaManager.scala:480)
        at kafka.server.ReplicaManager.$anonfun$asyncApplyDelta$5(ReplicaManager.scala:2538)
        at kafka.server.ReplicaManager$$Lambda$2502/0x00000008014e7b00.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.2/ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.2/ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(java.base@17.0.2/Thread.java:833)
```
