### ISSUE TITLE
`OUT_OF_ORDER_SEQUENCE_NUMBER` error by producers after moving partitions

### ISSUE THREAD

**Issue by Chillax-0v0** [AutoMQ/automq-for-kafka#509]
Move 1024 partitions from broker 1 to broker 2.

producer logs:
```
12:08:38.645 [kafka-producer-network-thread | producer-1] WARN Sender - [Producer clientId=producer-1] Got error produce response with correlation id 67570 on topic-partition test-topic-0000000-1024-441, retrying (2147482583 attempts left). Error: OUT_OF_ORDER_SEQUENCE_NUMBER
12:08:38.746 [kafka-producer-network-thread | producer-1] WARN Sender - [Producer clientId=producer-1] Got error produce response with correlation id 67603 on topic-partition test-topic-0000000-1024-117, retrying (2147482582 attempts left). Error: OUT_OF_ORDER_SEQUENCE_NUMBER
12:08:38.746 [kafka-producer-network-thread | producer-1] WARN Sender - [Producer clientId=producer-1] Got error produce response with correlation id 67603 on topic-partition test-topic-0000000-1024-608, retrying (2147482581 attempts left). Error: OUT_OF_ORDER_SEQUENCE_NUMBER
12:08:38.746 [kafka-producer-network-thread | producer-1] WARN Sender - [Producer clientId=producer-1] Got error produce response with correlation id 67603 on topic-partition test-topic-0000000-1024-441, retrying (2147482582 attempts left). Error: OUT_OF_ORDER_SEQUENCE_NUMBER
12:08:38.847 [kafka-producer-network-thread | producer-1] WARN Sender - [Producer clientId=producer-1] Got error produce response with correlation id 67636 on topic-partition test-topic-0000000-1024-117, retrying (2147482581 attempts left). Error: OUT_OF_ORDER_SEQUENCE_NUMBER
12:08:38.847 [kafka-producer-network-thread | producer-1] WARN Sender - [Producer clientId=producer-1] Got error produce response with correlation id 67636 on topic-partition test-topic-0000000-1024-608, retrying (2147482580 attempts left). Error: OUT_OF_ORDER_SEQUENCE_NUMBER
12:08:38.847 [kafka-producer-network-thread | producer-1] WARN Sender - [Producer clientId=producer-1] Got error produce response with correlation id 67636 on topic-partition test-topic-0000000-1024-441, retrying (2147482581 attempts left). Error: OUT_OF_ORDER_SEQUENCE_NUMBER
12:08:38.861 [main] INFO WorkloadGenerator - Pub rate  1280.600 msg/s /  5.002 MB/s | Pub err     0.000 err/s | Cons rate     0.000 msg/s /  0.000 MB/s | Backlog:  0.000 K | Pub Latency (ms) avg:  2.020 - 50%:  1.159 - 99%: 54.912 - 99.9%: 95.528 - Max: 98.651 | Pub Delay Latency (us) avg: 77.907 - 50%: 55.000 - 99%: 76.000 - 99.9%: 7157.000 - Max: 8633.000 | E2E Latency (ms) avg:  0.000 - 50%:  0.000 - 99%:  0.000 - 99.9%:  0.000 - Max:  0.000
12:08:38.906 [kafka-producer-network-thread | producer-1] WARN MessageProducer - Write error on message
java.util.concurrent.CompletionException: org.apache.kafka.common.errors.TimeoutException: Expiring 15 record(s) for test-topic-0000000-1024-441:120000 ms has passed since batch creation
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:781) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
	at io.openmessaging.benchmark.driver.kafka.KafkaBenchmarkProducer.lambda$sendAsync$0(KafkaBenchmarkProducer.java:56) ~[io.openmessaging.benchmark-driver-kafka-0.0.1-SNAPSHOT.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer$AppendCallbacks.onCompletion(KafkaProducer.java:1505) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.ProducerBatch.completeFutureAndFireCallbacks(ProducerBatch.java:273) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.ProducerBatch.done(ProducerBatch.java:234) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.ProducerBatch.completeExceptionally(ProducerBatch.java:198) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.failBatch(Sender.java:766) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.failBatch(Sender.java:751) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.sendProducerData(Sender.java:392) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:327) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: org.apache.kafka.common.errors.TimeoutException: Expiring 15 record(s) for test-topic-0000000-1024-441:120000 ms has passed since batch creation
12:08:38.907 [kafka-producer-network-thread | producer-1] WARN MessageProducer - Write error on message
java.util.concurrent.CompletionException: org.apache.kafka.common.errors.TimeoutException: Expiring 15 record(s) for test-topic-0000000-1024-441:120000 ms has passed since batch creation
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:781) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
	at io.openmessaging.benchmark.driver.kafka.KafkaBenchmarkProducer.lambda$sendAsync$0(KafkaBenchmarkProducer.java:56) ~[io.openmessaging.benchmark-driver-kafka-0.0.1-SNAPSHOT.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer$AppendCallbacks.onCompletion(KafkaProducer.java:1505) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.ProducerBatch.completeFutureAndFireCallbacks(ProducerBatch.java:273) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.ProducerBatch.done(ProducerBatch.java:234) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.ProducerBatch.completeExceptionally(ProducerBatch.java:198) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.failBatch(Sender.java:766) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.failBatch(Sender.java:751) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.sendProducerData(Sender.java:392) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:327) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: org.apache.kafka.common.errors.TimeoutException: Expiring 15 record(s) for test-topic-0000000-1024-441:120000 ms has passed since batch creation
```

broker 1:
```
ubuntu@ip-10-0-0-35:/data/kafka$ less logs/server.log | grep test-topic-0000000-1024-441
[2023-12-05 12:05:34,101] INFO [ReplicaFetcherManager on broker 3] Removed fetcher for partitions Set(test-topic-0000000-1024-441) (kafka.server.ReplicaFetcherManager)
[2023-12-05 12:05:34,282] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=2] opened existing meta stream: stream_id=1044 (kafka.log.streamaspect.ElasticLog$)
[2023-12-05 12:05:35,287] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=2] loaded partition meta: ElasticPartitionMeta{startOffset=0, cleanerOffset=0, recoverOffset=16, cleanedShutdown=true} (kafka.log.streamaspect.ElasticLog$)
[2023-12-05 12:05:35,287] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=2] loaded 1 producer snapshots, offsets(filenames) are Set(16)  (kafka.log.streamaspect.ElasticLog$)
[2023-12-05 12:05:35,481] INFO [ElasticProducerStateManager partition=test-topic-0000000-1024-441] Loading producer state from snapshot file 'SnapshotFile(16.snapshot,16)' (kafka.log.streamaspect.ElasticProducerStateManager)
[2023-12-05 12:05:35,562] INFO [ElasticLogLoader partition=test-topic-0000000-1024-441, dir=/data/data] Producer state recovery took 81ms for snapshot load and 0ms for segment recovery from offset 16 (kafka.log.streamaspect.ElasticUnifiedLog$)
[2023-12-05 12:05:35,577] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=2] loaded log meta: ElasticLogMeta{streamMap={log=1578, tim=2112, txn=-1}, lastNthSegmentMetas=[ElasticStreamSegmentMeta{baseOffset=0, createTimestamp=1701777893135, lastModifiedTimestamp=1701777930090, streamSuffix='', logSize=66656, log=[0, -1], time=[0, -1], txn=[0, -1], timeIndexLastEntry=TimestampOffsetData{timestamp=-1, offset=0}}]} (kafka.log.streamaspect.ElasticLog$)
[2023-12-05 12:05:35,577] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=2] loaded leader epoch checkpoint with 1 entries (kafka.log.streamaspect.ElasticLog$)
[2023-12-05 12:05:35,577] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=2] last leaderEpoch entry is: EpochEntry(epoch=0, startOffset=0) (kafka.log.streamaspect.ElasticLog$)
[2023-12-05 12:05:35,582] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=2] [ElasticLog partition=test-topic-0000000-1024-441 epoch=2] save partition meta ElasticPartitionMeta{startOffset=0, cleanerOffset=0, recoverOffset=16, cleanedShutdown=false} (kafka.log.streamaspect.ElasticLog)
[2023-12-05 12:05:35,917] INFO ElasticUnifiedLog test-topic-0000000-1024-441 opened time cost: 1671 ms (kafka.log.UnifiedLog$)
[2023-12-05 12:05:35,917] INFO Created log for partition test-topic-0000000-1024-441 in /data/data/test-topic-0000000-1024-441 with properties {elasticstream.replication.factor=3, flush.messages=1, min.insync.replicas=1, retention.ms=86400000}, cost=1678ms (kafka.log.LogManager)
[2023-12-05 12:05:35,917] INFO [Partition test-topic-0000000-1024-441 broker=3] Log loaded for partition test-topic-0000000-1024-441 with initial high watermark 16 (kafka.cluster.Partition)
[2023-12-05 12:06:39,479] INFO [ReplicaFetcherManager on broker 3] Removed fetcher for partitions Set(test-topic-0000000-1024-441) (kafka.server.ReplicaFetcherManager)
[2023-12-05 12:06:39,479] INFO [ReplicaAlterLogDirsManager on broker 3] Removed fetcher for partitions Set(test-topic-0000000-1024-441) (kafka.server.ReplicaAlterLogDirsManager)
[2023-12-05 12:06:39,480] INFO [Partition test-topic-0000000-1024-441 broker=3] Closing partition (kafka.cluster.Partition)
[2023-12-05 12:06:39,610] INFO [ElasticProducerStateManager partition=test-topic-0000000-1024-441] Wrote producer snapshot at offset 66 with 2 producer ids in 130 ms. (kafka.log.streamaspect.ElasticProducerStateManager)
[2023-12-05 12:06:39,767] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=2] save log meta ElasticLogMeta{streamMap={log=1578, tim=2112, txn=-1}, lastNthSegmentMetas=[ElasticStreamSegmentMeta{baseOffset=0, createTimestamp=1701777893135, lastModifiedTimestamp=1701777973333, streamSuffix='', logSize=274773, log=[0, -1], time=[0, -1], txn=[0, -1], timeIndexLastEntry=TimestampOffsetData{timestamp=-1, offset=0}}]} (kafka.log.streamaspect.ElasticLog$)
[2023-12-05 12:06:39,796] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=2] [ElasticLog partition=test-topic-0000000-1024-441 epoch=2] save partition meta ElasticPartitionMeta{startOffset=0, cleanerOffset=0, recoverOffset=66, cleanedShutdown=true} (kafka.log.streamaspect.ElasticLog)
[2023-12-05 12:06:39,806] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=2] log(except for streams) closed (kafka.log.streamaspect.ElasticLog)
[2023-12-05 12:06:44,627] INFO [ReplicaManager broker=3] partition test-topic-0000000-1024-441 is closed, trigger leader election (kafka.server.ReplicaManager)
```

broker 2:
```
ubuntu@ip-10-0-0-242:/data/kafka$ less logs/server.log | grep test-topic-0000000-1024-441
[2023-12-05 12:01:31,339] INFO [ReplicaFetcherManager on broker 2] Removed fetcher for partitions Set(test-topic-0000000-1024-441) (kafka.server.ReplicaFetcherManager)
[2023-12-05 12:01:31,340] INFO [ReplicaAlterLogDirsManager on broker 2] Removed fetcher for partitions Set(test-topic-0000000-1024-441) (kafka.server.ReplicaAlterLogDirsManager)
[2023-12-05 12:01:31,340] INFO [Partition test-topic-0000000-1024-441 broker=2] Closing partition (kafka.cluster.Partition)
[2023-12-05 12:01:31,449] INFO [ElasticProducerStateManager partition=test-topic-0000000-1024-441] Wrote producer snapshot at offset 5265 with 7 producer ids in 109 ms. (kafka.log.streamaspect.ElasticProducerStateManager)
[2023-12-05 12:01:31,502] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=10] save log meta ElasticLogMeta{streamMap={log=2572, tim=2778, txn=-1}, lastNthSegmentMetas=[ElasticStreamSegmentMeta{baseOffset=0, createTimestamp=1701776885943, lastModifiedTimestamp=1701777636024, streamSuffix='', logSize=21869358, log=[0, -1], time=[0, -1], txn=[0, -1], timeIndexLastEntry=TimestampOffsetData{timestamp=-1, offset=0}}]} (kafka.log.streamaspect.ElasticLog$)
[2023-12-05 12:01:31,546] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=10] [ElasticLog partition=test-topic-0000000-1024-441 epoch=10] save partition meta ElasticPartitionMeta{startOffset=0, cleanerOffset=0, recoverOffset=5265, cleanedShutdown=true} (kafka.log.streamaspect.ElasticLog)
[2023-12-05 12:01:31,558] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=10] log(except for streams) closed (kafka.log.streamaspect.ElasticLog)
[2023-12-05 12:01:33,837] INFO [ReplicaManager broker=2] partition test-topic-0000000-1024-441 is closed, trigger leader election (kafka.server.ReplicaManager)
[2023-12-05 12:06:49,349] INFO [ReplicaFetcherManager on broker 2] Removed fetcher for partitions Set(test-topic-0000000-1024-441) (kafka.server.ReplicaFetcherManager)
[2023-12-05 12:06:49,358] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=4] opened existing meta stream: stream_id=1044 (kafka.log.streamaspect.ElasticLog$)
[2023-12-05 12:06:50,754] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=4] loaded partition meta: ElasticPartitionMeta{startOffset=0, cleanerOffset=0, recoverOffset=66, cleanedShutdown=true} (kafka.log.streamaspect.ElasticLog$)
[2023-12-05 12:06:50,754] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=4] loaded 2 producer snapshots, offsets(filenames) are Set(16, 66)  (kafka.log.streamaspect.ElasticLog$)
[2023-12-05 12:06:50,761] INFO [ElasticProducerStateManager partition=test-topic-0000000-1024-441] Loading producer state from snapshot file 'SnapshotFile(66.snapshot,66)' (kafka.log.streamaspect.ElasticProducerStateManager)
[2023-12-05 12:06:50,761] INFO [ElasticLogLoader partition=test-topic-0000000-1024-441, dir=/data/data] Producer state recovery took 0ms for snapshot load and 0ms for segment recovery from offset 66 (kafka.log.streamaspect.ElasticUnifiedLog$)
[2023-12-05 12:06:50,761] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=4] loaded log meta: ElasticLogMeta{streamMap={log=1578, tim=2112, txn=-1}, lastNthSegmentMetas=[ElasticStreamSegmentMeta{baseOffset=0, createTimestamp=1701777893135, lastModifiedTimestamp=1701777973333, streamSuffix='', logSize=274773, log=[0, -1], time=[0, -1], txn=[0, -1], timeIndexLastEntry=TimestampOffsetData{timestamp=-1, offset=0}}]} (kafka.log.streamaspect.ElasticLog$)
[2023-12-05 12:06:50,761] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=4] loaded leader epoch checkpoint with 2 entries (kafka.log.streamaspect.ElasticLog$)
[2023-12-05 12:06:50,761] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=4] last leaderEpoch entry is: EpochEntry(epoch=2, startOffset=16) (kafka.log.streamaspect.ElasticLog$)
[2023-12-05 12:06:50,763] INFO [ElasticLog partition=test-topic-0000000-1024-441 epoch=4] [ElasticLog partition=test-topic-0000000-1024-441 epoch=4] save partition meta ElasticPartitionMeta{startOffset=0, cleanerOffset=0, recoverOffset=66, cleanedShutdown=false} (kafka.log.streamaspect.ElasticLog)
[2023-12-05 12:06:50,764] INFO ElasticUnifiedLog test-topic-0000000-1024-441 opened time cost: 1413 ms (kafka.log.UnifiedLog$)
[2023-12-05 12:06:50,764] INFO Created log for partition test-topic-0000000-1024-441 in /data/data/test-topic-0000000-1024-441 with properties {elasticstream.replication.factor=3, flush.messages=1, min.insync.replicas=1, retention.ms=86400000}, cost=1414ms (kafka.log.LogManager)
[2023-12-05 12:06:50,764] INFO [Partition test-topic-0000000-1024-441 broker=2] Log loaded for partition test-topic-0000000-1024-441 with initial high watermark 66 (kafka.cluster.Partition)
[2023-12-05 12:06:50,919] ERROR [ReplicaManager broker=2] Error processing append operation on partition test-topic-0000000-1024-441 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.OutOfOrderSequenceException: Out of order sequence number for producer 1 at offset 81 in partition test-topic-0000000-1024-441: 0 (incoming seq. number), 29 (current end sequence number)
[2023-12-05 12:06:51,026] ERROR [ReplicaManager broker=2] Error processing append operation on partition test-topic-0000000-1024-441 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.OutOfOrderSequenceException: Out of order sequence number for producer 1 at offset 96 in partition test-topic-0000000-1024-441: 0 (incoming seq. number), 29 (current end sequence number)
[2023-12-05 12:06:51,127] ERROR [ReplicaManager broker=2] Error processing append operation on partition test-topic-0000000-1024-441 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.OutOfOrderSequenceException: Out of order sequence number for producer 1 at offset 111 in partition test-topic-0000000-1024-441: 0 (incoming seq. number), 29 (current end sequence number)
[2023-12-05 12:06:51,228] ERROR [ReplicaManager broker=2] Error processing append operation on partition test-topic-0000000-1024-441 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.OutOfOrderSequenceException: Out of order sequence number for producer 1 at offset 111 in partition test-topic-0000000-1024-441: 0 (incoming seq. number), 29 (current end sequence number)
[2023-12-05 12:06:51,330] ERROR [ReplicaManager broker=2] Error processing append operation on partition test-topic-0000000-1024-441 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.OutOfOrderSequenceException: Out of order sequence number for producer 1 at offset 111 in partition test-topic-0000000-1024-441: 0 (incoming seq. number), 29 (current end sequence number)
[2023-12-05 12:06:51,430] ERROR [ReplicaManager broker=2] Error processing append operation on partition test-topic-0000000-1024-441 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.OutOfOrderSequenceException: Out of order sequence number for producer 1 at offset 111 in partition test-topic-0000000-1024-441: 0 (incoming seq. number), 29 (current end sequence number)
[2023-12-05 12:06:51,531] ERROR [ReplicaManager broker=2] Error processing append operation on partition test-topic-0000000-1024-441 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.OutOfOrderSequenceException: Out of order sequence number for producer 1 at offset 111 in partition test-topic-0000000-1024-441: 0 (incoming seq. number), 29 (current end sequence number)
...
[2023-12-05 12:07:48,686] ERROR [ReplicaManager broker=2] Error processing append operation on partition test-topic-0000000-1024-441 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.OutOfOrderSequenceException: Out of order sequence number for producer 1 at offset 127 in partition test-topic-0000000-1024-441: 0 (incoming seq. number), 29 (current end sequence number)
[2023-12-05 12:07:48,787] ERROR [ReplicaManager broker=2] Error processing append operation on partition test-topic-0000000-1024-441 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.OutOfOrderSequenceException: Out of order sequence number for producer 1 at offset 127 in partition test-topic-0000000-1024-441: 0 (incoming seq. number), 29 (current end sequence number)
[2023-12-05 12:07:48,888] ERROR [ReplicaManager broker=2] Error processing append operation on partition test-topic-0000000-1024-441 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.OutOfOrderSequenceException: Out of order sequence number for producer 1 at offset 127 in partition test-topic-0000000-1024-441: 0 (incoming seq. number), 29 (current end sequence number)
[2023-12-05 12:07:48,990] ERROR [ReplicaManager broker=2] Error processing append operation on partition test-topic-0000000-1024-441 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.OutOfOrderSequenceException: Out of order sequence number for producer 1 at offset 147 in partition test-topic-0000000-1024-441: 0 (incoming seq. number), 49 (current end sequence number)
[2023-12-05 12:07:49,092] ERROR [ReplicaManager broker=2] Error processing append operation on partition test-topic-0000000-1024-441 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.OutOfOrderSequenceException: Out of order sequence number for producer 1 at offset 147 in partition test-topic-0000000-1024-441: 0 (incoming seq. number), 49 (current end sequence number)
[2023-12-05 12:07:49,193] ERROR [ReplicaManager broker=2] Error processing append operation on partition test-topic-0000000-1024-441 (kafka.server.ReplicaManager)
...
```

**Comment by superhx** [comment]
https://github.com/AutoMQ/automq-for-kafka/pull/590
