### ISSUE TITLE
`CorruptRecordException` during catch-up read

### ISSUE THREAD

**Issue by Chillax-0v0** [AutoMQ/automq-for-kafka#560]
client1:
```
10:03:56.979 [kafka-admin-client-thread | adminclient-2] INFO NetworkClient - [AdminClient clientId=adminclient-2] Node 19 disconnected.
10:08:57.083 [kafka-admin-client-thread | adminclient-2] INFO NetworkClient - [AdminClient clientId=adminclient-2] Node 0 disconnected.
10:13:57.187 [kafka-admin-client-thread | adminclient-2] INFO NetworkClient - [AdminClient clientId=adminclient-2] Node 5 disconnected.
10:18:57.291 [kafka-admin-client-thread | adminclient-2] INFO NetworkClient - [AdminClient clientId=adminclient-2] Node 10 disconnected.
10:18:57.294 [pool-3-thread-1] INFO NetworkClient - [Consumer clientId=consumer-sub-000-2, groupId=sub-000] Node 2 disconnected.
10:18:57.380 [pool-3-thread-1] INFO NetworkClient - [Consumer clientId=consumer-sub-000-2, groupId=sub-000] Node 10 disconnected.
10:18:57.380 [pool-3-thread-1] INFO NetworkClient - [Consumer clientId=consumer-sub-000-2, groupId=sub-000] Cancelled in-flight FETCH request with correlation id 878429 due to node 10 being disconnected (elapsed time since creation: 1ms, elapsed time si
nce send: 1ms, request timeout: 30000ms)
10:18:57.386 [pool-3-thread-1] INFO FetchSessionHandler - [Consumer clientId=consumer-sub-000-2, groupId=sub-000] Error sending fetch request (sessionId=1571351525, epoch=41395) to node 10:
org.apache.kafka.common.errors.DisconnectException: null
10:23:57.395 [kafka-admin-client-thread | adminclient-2] INFO NetworkClient - [AdminClient clientId=adminclient-2] Node 7 disconnected.
10:23:57.495 [pool-3-thread-1] ERROR KafkaBenchmarkConsumer - exception occur while consuming message
org.apache.kafka.common.errors.CorruptRecordException: Record size -2147483444 is less than the minimum record overhead (14)
10:23:57.495 [pool-3-thread-1] ERROR KafkaBenchmarkConsumer - exception occur while consuming message
org.apache.kafka.common.errors.CorruptRecordException: Record size -2147483444 is less than the minimum record overhead (14)
10:23:57.495 [pool-3-thread-1] ERROR KafkaBenchmarkConsumer - exception occur while consuming message
org.apache.kafka.common.errors.CorruptRecordException: Record size -2147483444 is less than the minimum record overhead (14)
10:23:57.495 [pool-3-thread-1] ERROR KafkaBenchmarkConsumer - exception occur while consuming message
org.apache.kafka.common.errors.CorruptRecordException: Record size -2147483444 is less than the minimum record overhead (14)
10:23:57.496 [pool-3-thread-1] ERROR KafkaBenchmarkConsumer - exception occur while consuming message
org.apache.kafka.common.errors.CorruptRecordException: Record size -2147483444 is less than the minimum record overhead (14)
```

client2:
```
10:03:56.994 [kafka-admin-client-thread | adminclient-2] INFO NetworkClient - [AdminClient clientId=adminclient-2] Node 10 disconnected.
10:08:57.098 [kafka-admin-client-thread | adminclient-2] INFO NetworkClient - [AdminClient clientId=adminclient-2] Node 14 disconnected.
10:08:57.142 [pool-3-thread-1] ERROR KafkaBenchmarkConsumer - exception occur while consuming message
org.apache.kafka.common.KafkaException: Received exception when fetching the next record from test-topic-0000000-1000-641. If needed, please seek past the record to continue consumption.
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1642) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1900(Fetcher.java:1497) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:717) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:683) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1287) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1243) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at io.openmessaging.benchmark.driver.kafka.KafkaBenchmarkConsumer.lambda$new$0(KafkaBenchmarkConsumer.java:62) ~[io.openmessaging.benchmark-driver-kafka-0.0.1-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: org.apache.kafka.common.KafkaException: Record batch for partition test-topic-0000000-1000-641 at offset 464325 is invalid, cause: Record is corrupt (stored crc = 3387419869, computed crc = 1075619168)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.maybeEnsureValid(Fetcher.java:1555) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.nextFetchedRecord(Fetcher.java:1599) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1656) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        ... 12 more
10:08:57.152 [pool-3-thread-1] ERROR KafkaBenchmarkConsumer - exception occur while consuming message
org.apache.kafka.common.KafkaException: Received exception when fetching the next record from test-topic-0000000-1000-641. If needed, please seek past the record to continue consumption.
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1642) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1900(Fetcher.java:1497) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:717) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:683) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1287) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1243) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at io.openmessaging.benchmark.driver.kafka.KafkaBenchmarkConsumer.lambda$new$0(KafkaBenchmarkConsumer.java:62) ~[io.openmessaging.benchmark-driver-kafka-0.0.1-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: org.apache.kafka.common.KafkaException: Record batch for partition test-topic-0000000-1000-641 at offset 464325 is invalid, cause: Record is corrupt (stored crc = 3387419869, computed crc = 1075619168)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.maybeEnsureValid(Fetcher.java:1555) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.nextFetchedRecord(Fetcher.java:1599) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1656) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        ... 12 more
```

client3:
```
10:03:56.991 [pool-3-thread-1] INFO NetworkClient - [Consumer clientId=consumer-sub-000-2, groupId=sub-000] Node 1 disconnected.
10:03:56.991 [pool-3-thread-1] INFO NetworkClient - [Consumer clientId=consumer-sub-000-2, groupId=sub-000] Cancelled in-flight FETCH request with correlation id 755267 due to node 1 being disconnected (elapsed time since creation: 6ms, elapsed time sin
ce send: 6ms, request timeout: 30000ms)
10:03:56.998 [kafka-admin-client-thread | adminclient-2] INFO NetworkClient - [AdminClient clientId=adminclient-2] Node 11 disconnected.
10:03:56.992 [pool-3-thread-1] INFO FetchSessionHandler - [Consumer clientId=consumer-sub-000-2, groupId=sub-000] Error sending fetch request (sessionId=577134981, epoch=39614) to node 1:
org.apache.kafka.common.errors.DisconnectException: null
10:03:57.054 [pool-3-thread-1] ERROR KafkaBenchmarkConsumer - exception occur while consuming message
org.apache.kafka.common.KafkaException: Received exception when fetching the next record from test-topic-0000000-1000-309. If needed, please seek past the record to continue consumption.
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1642) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1900(Fetcher.java:1497) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:717) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:683) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1287) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1243) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at io.openmessaging.benchmark.driver.kafka.KafkaBenchmarkConsumer.lambda$new$0(KafkaBenchmarkConsumer.java:62) ~[io.openmessaging.benchmark-driver-kafka-0.0.1-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: org.apache.kafka.common.KafkaException: Record batch for partition test-topic-0000000-1000-309 at offset 151330 is invalid, cause: Record is corrupt (stored crc = 1900720524, computed crc = 3548296692)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.maybeEnsureValid(Fetcher.java:1555) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.nextFetchedRecord(Fetcher.java:1599) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1656) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1900(Fetcher.java:1497) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:717) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:683) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1314) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        ... 8 more
10:03:57.058 [pool-3-thread-1] ERROR KafkaBenchmarkConsumer - exception occur while consuming message
org.apache.kafka.common.KafkaException: Received exception when fetching the next record from test-topic-0000000-1000-309. If needed, please seek past the record to continue consumption.
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1642) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1900(Fetcher.java:1497) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:717) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:683) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1287) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1243) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at io.openmessaging.benchmark.driver.kafka.KafkaBenchmarkConsumer.lambda$new$0(KafkaBenchmarkConsumer.java:62) ~[io.openmessaging.benchmark-driver-kafka-0.0.1-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: org.apache.kafka.common.KafkaException: Record batch for partition test-topic-0000000-1000-309 at offset 151330 is invalid, cause: Record is corrupt (stored crc = 1900720524, computed crc = 3548296692)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.maybeEnsureValid(Fetcher.java:1555) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.nextFetchedRecord(Fetcher.java:1599) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1656) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1900(Fetcher.java:1497) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:717) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:683) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1314) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
        ... 8 more
```

**Comment by Chillax-0v0** [comment]
fixed by #555
