### ISSUE TITLE
read from block cache failed

### ISSUE THREAD

**Issue by mooc9988** [AutoMQ/automq-for-kafka#563]
ip: 52.83.6.149
```
[2023-12-14 02:27:04,461] ERROR read from block cache failed, stream=29, 77473342-65536, maxBytes: {} (com.automq.stream.s3.S3Storage)
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Continuous check failed...StreamRecordBatch{streamId=29, epoch=0, baseOffset=77473787, count=1, size=188}]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at com.automq.stream.s3.cache.DefaultS3BlockCache.lambda$read$0(DefaultS3BlockCache.java:108)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at com.automq.stream.utils.FutureUtil.lambda$propagate$0(FutureUtil.java:51)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:653)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalArgumentException: Continuous check failed, expect offset: 77473770, actual: 77473782, ..., StreamRecordBatch{streamId=29, epoch=0, baseOffset=77473787, count=1, size=188}]
        at com.automq.stream.s3.S3Storage.continuousCheck(S3Storage.java:398)
        at com.automq.stream.s3.S3Storage.lambda$read0$13(S3Storage.java:380)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        ... 17 more
```

**Comment by SCNieh** [comment]
logs/server.log.2023-12-14-02:[2023-12-14 02:28:25,578] INFO Upload delta WAL CommitStreamSetObjectRequest{objectId=148323, orderId=148323, objectSize=9446548, streamRanges=[(29--1,78187983-78187985-376), (67--1,84241733-84297936-7582013), (83--1,32019144-32040852-21708), (185--1,270603960-270651204-47244), (190--1,273087084-273134844-47760)], streamObjects=[StreamObject{objectId=148324, objectSize=49065858, streamId=176, startOffset=275224059, endOffset=275269240, sourceObjectIds=null}, StreamObject{objectId=148325, objectSize=49079816, streamId=183, startOffset=275224064, endOffset=275269248, sourceObjectIds=null}], compactedObjectIds=null}, cost 4469ms, rate limiter 3.5390127910901114E7bytes/s (com.automq.stream.s3.DeltaWALUploadTask)

**Comment by SCNieh** [comment]
next = StreamRecordBatch{streamId=67, epoch=0, baseOffset=84265682, count=1, size=149}
next = StreamRecordBatch{streamId=67, epoch=0, baseOffset=84265683, count=1, size=149}
next = StreamRecordBatch{streamId=67, epoch=0, baseOffset=84265685, count=1, size=149}
next = StreamRecordBatch{streamId=67, epoch=0, baseOffset=84265686, count=2, size=237}
