### ISSUE TITLE
producer throw OUT_OF_ORDER_SEQUENCE_NUMBER exception

### ISSUE THREAD

**Issue by mooc9988** [AutoMQ/automq-for-kafka#584]
client log:
```
10:58:49.285 [qtp936219350-30] INFO KafkaProducer - [Producer clientId=producer-1] Instantiated an idempotent producer.
10:58:49.310 [kafka-producer-network-thread | producer-1] INFO Metadata - [Producer clientId=producer-1] Cluster ID: rZdE0DjZSrqy96PXrMUZVw
10:58:49.310 [kafka-producer-network-thread | producer-1] INFO TransactionManager - [Producer clientId=producer-1] ProducerId set to 2 with epoch 0
10:58:49.404 [kafka-producer-network-thread | producer-1] INFO Metadata - [Producer clientId=producer-1] Resetting the last seen epoch of partition testMain-0 to 0 since the associated topicId changed from null to c5ZTCneZTs6uiboF6wWNcg
10:58:49.478 [kafka-producer-network-thread | producer-1] WARN Sender - [Producer clientId=producer-1] Got error produce response with correlation id 5 on topic-partition testMain-0, retrying (2147483646 attempts left). Error: NOT_LEADER_OR_FOLLOWER
10:58:49.478 [kafka-producer-network-thread | producer-1] WARN Sender - [Producer clientId=producer-1] Received invalid metadata error in produce request on partition testMain-0 due to org.apache.kafka.common.errors.NotLeaderOrFollowerException: For requests intended only for the leader, this error indicates that the broker is not the current leader. For requests intended for any replica, this error indicates that the broker is not a replica of the topic partition.. Going to request metadata update now
10:58:49.606 [kafka-producer-network-thread | producer-1] WARN Sender - [Producer clientId=producer-1] Got error produce response with correlation id 20 on topic-partition testMain-0, retrying (2147483645 attempts left). Error: OUT_OF_ORDER_SEQUENCE_NUMBER
```

server.log
```
[2023-12-20 10:58:49,479] INFO [Partition testMain-0 broker=1] Log loaded for partition testMain-0 with initial high watermark 0 (kafka.cluster.Partition)
[2023-12-20 10:58:49,485] INFO [KafkaApi-1] produce cost (in microseconds), produce={count=1, max=1622.0, mean=1622.0} callback={count=2, max=45853.0, mean=23134.5} ack={count=2, max=4018.0, mean=2091.5} (kafka.server.KafkaApis)
[2023-12-20 10:58:49,493] INFO [ReplicaManager broker=1] open 6 / close 0 partitions cost 237ms (kafka.server.ReplicaManager)
[2023-12-20 10:58:49,534] INFO log append cost, permitAcquireFail={count=0, max=0.0, mean=0.0}, remainingPermit=104857600/104857600, append={count=2, max=3432635.0, mean=2671556.0}, callback={count=2, max=5786831.0, mean=5015459.0}, ack={count=1, max=8117269.0, mean=8117269.0} (kafka.log.streamaspect.ElasticLog)
[2023-12-20 10:58:49,588] ERROR [ReplicaManager broker=1] Error processing append operation on partition testMain-0 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.OutOfOrderSequenceException: Out of order sequence number for producer 2 at offset 91 in partition testMain-0: 0 (incoming seq. number), 91 (current end sequence number)
```

**Comment by mooc9988** [comment]
client timeout 2min later:
```
11:00:49.325 [kafka-producer-network-thread | producer-1] WARN Sender - [Producer clientId=producer-1] Got error produce response with correlation id 180985 on topic-partition testMain-0, retrying (2147482481 attempts left). Error: OUT_OF_ORDER_SEQUENCE_NUMBER
11:00:49.413 [kafka-producer-network-thread | producer-1] WARN MessageProducer - Write error on message
java.util.concurrent.CompletionException: org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for testMain-0:120000 ms has passed since batch creation
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:781) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
	at io.openmessaging.benchmark.driver.kafka.KafkaBenchmarkProducer.lambda$sendAsync$2(KafkaBenchmarkProducer.java:114) ~[io.openmessaging.benchmark-driver-kafka-0.0.1-SNAPSHOT.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer$AppendCallbacks.onCompletion(KafkaProducer.java:1505) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.ProducerBatch.completeFutureAndFireCallbacks(ProducerBatch.java:273) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.ProducerBatch.done(ProducerBatch.java:234) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.ProducerBatch.completeExceptionally(ProducerBatch.java:198) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.failBatch(Sender.java:766) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.failBatch(Sender.java:751) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.sendProducerData(Sender.java:392) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:327) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243) [org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for testMain-0:120000 ms has passed since batch creation
```

**Comment by mooc9988** [comment]
What happened:
* [Producer clientId=producer-1] sent batch 0 before 10:58:49,479 and got NOT_LEADER_OR_FOLLOWER since the topic-partition testMain-0 has not been opened.
* topic-partition testMain-0 opened in 10:58:49,479;
* [Producer clientId=producer-1] sent batch 1 successfully. As a result, first seq id in producer state manager is NOT 0.
* [Producer clientId=producer-1] sent batch 0 again with OUT_OF_ORDER_SEQUENCE_NUMBER exception.
