### ISSUE TITLE
`RecordBatchTooLargeException` during trim stream

### ISSUE THREAD

**Issue by Chillax-0v0** [AutoMQ/automq-for-kafka#603]
controller.log
```
[2023-12-27 03:23:57,710] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 609 success, compacted objects: [0, 83], stream range: [ObjectStreamRange(streamId=0, streamEpoch=0, startOffset=0, endOffset=4), ObjectStreamRange(streamId=>
[2023-12-27 03:24:45,310] INFO [Controller 1] CreateTopics result(s): CreatableTopic(name='test-topic-0000000-5000', numPartitions=5000, replicationFactor=3, assignments=[], configs=[CreateableTopicConfig(name='min.insync.replicas', value='2'), Createa>
[2023-12-27 03:25:15,356] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2660 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=0, streamEpoch=0, startOffset=7, endOffset=9), ObjectStreamRange(streamId=1, s>
[2023-12-27 03:25:27,313] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2661 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=50, streamEpoch=0, startOffset=9298, endOffset=9492), ObjectStreamRange(stream>
[2023-12-27 03:25:39,360] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2662 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=49, streamEpoch=0, startOffset=9168, endOffset=9453), ObjectStreamRange(stream>
[2023-12-27 03:25:51,453] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2663 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=50, streamEpoch=0, startOffset=9630, endOffset=9780), ObjectStreamRange(stream>
[2023-12-27 03:26:04,238] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2664 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=49, streamEpoch=0, startOffset=9453, endOffset=9594), ObjectStreamRange(stream>
[2023-12-27 03:26:16,703] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2665 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=49, streamEpoch=0, startOffset=9594, endOffset=9663), ObjectStreamRange(stream>
[2023-12-27 03:26:29,335] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2666 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=50, streamEpoch=0, startOffset=9925, endOffset=10085), ObjectStreamRange(strea>
[2023-12-27 03:26:41,885] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2667 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=49, streamEpoch=0, startOffset=9663, endOffset=9759), ObjectStreamRange(stream>
[2023-12-27 03:26:54,604] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2668 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=52, streamEpoch=0, startOffset=8209, endOffset=8375), ObjectStreamRange(stream>
[2023-12-27 03:27:07,476] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2669 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=50, streamEpoch=0, startOffset=10287, endOffset=10457), ObjectStreamRange(stre>
[2023-12-27 03:27:19,867] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2670 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=49, streamEpoch=0, startOffset=9759, endOffset=9903), ObjectStreamRange(stream>
[2023-12-27 03:27:32,523] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2671 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=49, streamEpoch=0, startOffset=9903, endOffset=10081), ObjectStreamRange(strea>
[2023-12-27 03:27:45,201] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2672 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=49, streamEpoch=0, startOffset=10081, endOffset=10339), ObjectStreamRange(stre>
[2023-12-27 03:27:57,764] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2673 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=49, streamEpoch=0, startOffset=10339, endOffset=10510), ObjectStreamRange(stre>
[2023-12-27 03:28:10,474] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2674 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=49, streamEpoch=0, startOffset=10510, endOffset=10688), ObjectStreamRange(stre>
[2023-12-27 03:28:23,129] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2675 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=50, streamEpoch=0, startOffset=11125, endOffset=11203), ObjectStreamRange(stre>
[2023-12-27 03:28:35,720] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2676 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=49, streamEpoch=0, startOffset=10688, endOffset=10847), ObjectStreamRange(stre>
[2023-12-27 03:28:48,447] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2677 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=49, streamEpoch=0, startOffset=10847, endOffset=11104), ObjectStreamRange(stre>
[2023-12-27 03:29:01,245] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2678 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=49, streamEpoch=0, startOffset=11104, endOffset=11197), ObjectStreamRange(stre>
[2023-12-27 03:29:13,694] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2679 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=50, streamEpoch=0, startOffset=11203, endOffset=11293), ObjectStreamRange(stre>
[2023-12-27 03:29:26,462] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2680 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=49, streamEpoch=0, startOffset=11197, endOffset=11278), ObjectStreamRange(stre>
[2023-12-27 03:29:38,831] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2681 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=49, streamEpoch=0, startOffset=11278, endOffset=11435), ObjectStreamRange(stre>
[2023-12-27 03:29:51,604] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2682 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=50, streamEpoch=0, startOffset=11377, endOffset=11492), ObjectStreamRange(stre>
[2023-12-27 03:30:04,290] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2683 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=49, streamEpoch=0, startOffset=11435, endOffset=11499), ObjectStreamRange(stre>
[2023-12-27 03:30:16,922] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2684 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=50, streamEpoch=0, startOffset=11564, endOffset=11649), ObjectStreamRange(stre>
[2023-12-27 03:30:29,493] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2685 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=52, streamEpoch=0, startOffset=10595, endOffset=10752), ObjectStreamRange(stre>
[2023-12-27 03:30:42,319] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2686 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=52, streamEpoch=0, startOffset=10752, endOffset=11031), ObjectStreamRange(stre>
[2023-12-27 03:30:54,899] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2687 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=49, streamEpoch=0, startOffset=11499, endOffset=11744), ObjectStreamRange(stre>
[2023-12-27 03:31:07,319] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2688 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=50, streamEpoch=0, startOffset=11649, endOffset=11810), ObjectStreamRange(stre>
[2023-12-27 03:31:20,258] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2689 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=49, streamEpoch=0, startOffset=11744, endOffset=11870), ObjectStreamRange(stre>
[2023-12-27 03:31:33,056] INFO [Controller 1] [CommitStreamSetObject]: nodeId=1 commit object: 2690 success, compacted objects: [], stream range: [ObjectStreamRange(streamId=50, streamEpoch=0, startOffset=11810, endOffset=12055), ObjectStreamRange(stre>
[2023-12-27 03:31:41,851] INFO [Controller 1] [CreateStream] create streamId=15150 success (org.apache.kafka.controller.stream.StreamControlManager)
[2023-12-27 03:31:41,875] INFO [Controller 1] [OpenStream] nodeId=1 open streamId=15150 with epoch=2 success (org.apache.kafka.controller.stream.StreamControlManager)
[2023-12-27 03:31:43,730] INFO [Controller 1] [CreateStream] create streamId=15151 success (org.apache.kafka.controller.stream.StreamControlManager)
[2023-12-27 03:31:43,734] INFO [Controller 1] [OpenStream] nodeId=1 open streamId=15151 with epoch=2 success (org.apache.kafka.controller.stream.StreamControlManager)
[2023-12-27 03:31:44,252] INFO [Controller 1] [TrimStream] nodeId=1 trim streamId=14886 to new start offset=1435003 with epoch=2 success (org.apache.kafka.controller.stream.StreamControlManager)
[2023-12-27 03:31:44,838] WARN [Controller 1] trimStream: failed with unknown server exception RuntimeException at epoch 2 in 1003527 us.  Renouncing leadership and reverting to the last committed offset 143643. (org.apache.kafka.controller.QuorumContr>
java.lang.RuntimeException: org.apache.kafka.common.errors.RecordBatchTooLargeException: The total record(s) size of 10361644 exceeds the maximum allowed batch size of 8388608
        at org.apache.kafka.controller.QuorumController.appendRecords(QuorumController.java:895)
        at org.apache.kafka.controller.QuorumController$ControllerWriteEvent.run(QuorumController.java:766)
        at org.apache.kafka.queue.KafkaEventQueue$EventContext.run(KafkaEventQueue.java:121)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.handleEvents(KafkaEventQueue.java:201)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.run(KafkaEventQueue.java:175)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.kafka.common.errors.RecordBatchTooLargeException: The total record(s) size of 10361644 exceeds the maximum allowed batch size of 8388608
[2023-12-27 03:31:44,887] ERROR [Controller 1] trimStream: unable to start processing because of NotControllerException. (org.apache.kafka.controller.QuorumController)
[2023-12-27 03:31:44,948] ERROR [Controller 1] trimStream: unable to start processing because of NotControllerException. (org.apache.kafka.controller.QuorumController)
[2023-12-27 03:31:45,001] ERROR [Controller 1] trimStream: unable to start processing because of NotControllerException. (org.apache.kafka.controller.QuorumController)
[2023-12-27 03:31:45,056] ERROR [Controller 1] trimStream: unable to start processing because of NotControllerException. (org.apache.kafka.controller.QuorumController)
[2023-12-27 03:31:45,083] ERROR [Controller 1] processBrokerHeartbeat: unable to start processing because of NotControllerException. (org.apache.kafka.controller.QuorumController)
[2023-12-27 03:31:45,110] ERROR [Controller 1] trimStream: unable to start processing because of NotControllerException. (org.apache.kafka.controller.QuorumController)
```

**Comment by Chillax-0v0** [comment]
after a while, controller.log:
```
[2023-12-27 03:32:02,443] ERROR [Controller 1] processBrokerHeartbeat: unable to start processing because of NotControllerException. (org.apache.kafka.controller.QuorumController)
[2023-12-27 03:32:02,464] INFO [Controller 1] In the new epoch 7, the leader is (none). (org.apache.kafka.controller.QuorumController)
[2023-12-27 03:32:02,470] INFO [Controller 1] Becoming the active controller at epoch 7, committed offset 143678, committed epoch 6 (org.apache.kafka.controller.QuorumController)
[2023-12-27 03:32:03,788] ERROR [Controller 1] object 2627 not exist when mark destroy object (org.apache.kafka.controller.stream.S3ObjectControlManager)
[2023-12-27 03:32:03,788] ERROR [Controller 1] [TrimStream] Mark destroy stream object: 2627 failed (org.apache.kafka.controller.stream.StreamControlManager)
[2023-12-27 03:32:06,310] WARN [Controller 1] checkS3ObjectsLifecycle: failed with unknown server exception NullPointerException at epoch 7 in 283 us.  Renouncing leadership and reverting to the last committed offset 143689. (org.apache.kafka.controlle>
java.lang.NullPointerException: Cannot invoke "org.apache.kafka.metadata.stream.S3Object.getMarkDestroyedTimeInMs()" because "obj" is null
        at org.apache.kafka.controller.stream.S3ObjectControlManager.lambda$checkS3ObjectsLifecycle$3(S3ObjectControlManager.java:278)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.concurrent.LinkedBlockingDeque.forEachFrom(LinkedBlockingDeque.java:1325)
        at java.base/java.util.concurrent.LinkedBlockingDeque$LBDSpliterator.forEachRemaining(LinkedBlockingDeque.java:1257)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.apache.kafka.controller.stream.S3ObjectControlManager.checkS3ObjectsLifecycle(S3ObjectControlManager.java:280)
        at org.apache.kafka.controller.QuorumController.lambda$checkS3ObjectsLifecycle$32(QuorumController.java:2315)
        at org.apache.kafka.controller.QuorumController$ControllerWriteEvent.run(QuorumController.java:742)
        at org.apache.kafka.queue.KafkaEventQueue$EventContext.run(KafkaEventQueue.java:121)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.handleEvents(KafkaEventQueue.java:201)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.run(KafkaEventQueue.java:175)
        at java.base/java.lang.Thread.run(Thread.java:840)
[2023-12-27 03:32:06,310] ERROR [Controller 1] Failed to check the S3Object's lifecycle (org.apache.kafka.controller.stream.S3ObjectControlManager)
org.apache.kafka.common.errors.UnknownServerException: java.lang.NullPointerException: Cannot invoke "org.apache.kafka.metadata.stream.S3Object.getMarkDestroyedTimeInMs()" because "obj" is null
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.kafka.metadata.stream.S3Object.getMarkDestroyedTimeInMs()" because "obj" is null
        at org.apache.kafka.controller.stream.S3ObjectControlManager.lambda$checkS3ObjectsLifecycle$3(S3ObjectControlManager.java:278)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.concurrent.LinkedBlockingDeque.forEachFrom(LinkedBlockingDeque.java:1325)
        at java.base/java.util.concurrent.LinkedBlockingDeque$LBDSpliterator.forEachRemaining(LinkedBlockingDeque.java:1257)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.apache.kafka.controller.stream.S3ObjectControlManager.checkS3ObjectsLifecycle(S3ObjectControlManager.java:280)
        at org.apache.kafka.controller.QuorumController.lambda$checkS3ObjectsLifecycle$32(QuorumController.java:2315)
        at org.apache.kafka.controller.QuorumController$ControllerWriteEvent.run(QuorumController.java:742)
        at org.apache.kafka.queue.KafkaEventQueue$EventContext.run(KafkaEventQueue.java:121)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.handleEvents(KafkaEventQueue.java:201)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.run(KafkaEventQueue.java:175)
        at java.base/java.lang.Thread.run(Thread.java:840)
[2023-12-27 03:32:06,498] ERROR [Controller 1] processBrokerHeartbeat: unable to start processing because of NotControllerException. (org.apache.kafka.controller.QuorumController)
```
