### ISSUE TITLE
Consumer report "Unexpected error code 7 while fetching at offset xxx"

### ISSUE THREAD

**Issue by Chillax-0v0** [AutoMQ/automq-for-kafka#616]
client.log:
```
04:38:03.197 [pool-168-thread-1] ERROR KafkaBenchmarkConsumer - exception occur while consuming message
java.lang.IllegalStateException: Unexpected error code 7 while fetching at offset 10861 from topic-partition test-topic-0000049-0008-3
	at org.apache.kafka.clients.consumer.internals.Fetcher.initializeCompletedFetch(Fetcher.java:1382) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:659) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1287) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1243) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at io.openmessaging.benchmark.driver.kafka.KafkaBenchmarkConsumer.lambda$new$0(KafkaBenchmarkConsumer.java:62) ~[io.openmessaging.benchmark-driver-kafka-0.0.1-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
04:38:03.197 [pool-168-thread-1] ERROR KafkaBenchmarkConsumer - exception occur while consuming message
java.lang.IllegalStateException: Unexpected error code 7 while fetching at offset 10344 from topic-partition test-topic-0000049-0008-4
	at org.apache.kafka.clients.consumer.internals.Fetcher.initializeCompletedFetch(Fetcher.java:1382) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:659) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1287) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1243) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at io.openmessaging.benchmark.driver.kafka.KafkaBenchmarkConsumer.lambda$new$0(KafkaBenchmarkConsumer.java:62) ~[io.openmessaging.benchmark-driver-kafka-0.0.1-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
04:38:03.197 [pool-168-thread-1] ERROR KafkaBenchmarkConsumer - exception occur while consuming message
java.lang.IllegalStateException: Unexpected error code 7 while fetching at offset 10167 from topic-partition test-topic-0000049-0008-1
	at org.apache.kafka.clients.consumer.internals.Fetcher.initializeCompletedFetch(Fetcher.java:1382) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:659) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1287) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1243) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at io.openmessaging.benchmark.driver.kafka.KafkaBenchmarkConsumer.lambda$new$0(KafkaBenchmarkConsumer.java:62) ~[io.openmessaging.benchmark-driver-kafka-0.0.1-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
04:38:03.197 [pool-168-thread-1] ERROR KafkaBenchmarkConsumer - exception occur while consuming message
java.lang.IllegalStateException: Unexpected error code 7 while fetching at offset 9052 from topic-partition test-topic-0000049-0008-0
	at org.apache.kafka.clients.consumer.internals.Fetcher.initializeCompletedFetch(Fetcher.java:1382) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:659) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1287) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1243) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216) ~[org.apache.kafka-kafka-clients-3.4.0.jar:?]
	at io.openmessaging.benchmark.driver.kafka.KafkaBenchmarkConsumer.lambda$new$0(KafkaBenchmarkConsumer.java:62) ~[io.openmessaging.benchmark-driver-kafka-0.0.1-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

server.log:
```
[2023-12-29 04:38:03,110] WARN [ReplicaManager broker=1] Returning emtpy fetch response for fetch request ArrayBuffer((kJBtPCJaRV-f7GNBJi2Ktw:test-topic-0000045-0008-1,PartitionData(topicId=kJBtPCJaRV-f7GNBJi2Ktw, fetchOffset=10849, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (kJBtPCJaRV-f7GNBJi2Ktw:test-topic-0000045-0008-3,PartitionData(topicId=kJBtPCJaRV-f7GNBJi2Ktw, fetchOffset=9720, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (kJBtPCJaRV-f7GNBJi2Ktw:test-topic-0000045-0008-5,PartitionData(topicId=kJBtPCJaRV-f7GNBJi2Ktw, fetchOffset=10690, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (kJBtPCJaRV-f7GNBJi2Ktw:test-topic-0000045-0008-0,PartitionData(topicId=kJBtPCJaRV-f7GNBJi2Ktw, fetchOffset=9213, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (kJBtPCJaRV-f7GNBJi2Ktw:test-topic-0000045-0008-7,PartitionData(topicId=kJBtPCJaRV-f7GNBJi2Ktw, fetchOffset=11455, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (kJBtPCJaRV-f7GNBJi2Ktw:test-topic-0000045-0008-6,PartitionData(topicId=kJBtPCJaRV-f7GNBJi2Ktw, fetchOffset=8365, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (kJBtPCJaRV-f7GNBJi2Ktw:test-topic-0000045-0008-4,PartitionData(topicId=kJBtPCJaRV-f7GNBJi2Ktw, fetchOffset=10074, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (kJBtPCJaRV-f7GNBJi2Ktw:test-topic-0000045-0008-2,PartitionData(topicId=kJBtPCJaRV-f7GNBJi2Ktw, fetchOffset=10476, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty))) since the wait time 500 exceed 500 ms. (kafka.server.ReplicaManager)
[2023-12-29 04:38:03,111] WARN [ReplicaManager broker=1] Returning emtpy fetch response for fetch request ArrayBuffer((7CMdqCPDQ62proT7qiw6vA:test-topic-0000044-0008-3,PartitionData(topicId=7CMdqCPDQ62proT7qiw6vA, fetchOffset=10688, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (7CMdqCPDQ62proT7qiw6vA:test-topic-0000044-0008-2,PartitionData(topicId=7CMdqCPDQ62proT7qiw6vA, fetchOffset=9729, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (7CMdqCPDQ62proT7qiw6vA:test-topic-0000044-0008-1,PartitionData(topicId=7CMdqCPDQ62proT7qiw6vA, fetchOffset=8769, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (7CMdqCPDQ62proT7qiw6vA:test-topic-0000044-0008-0,PartitionData(topicId=7CMdqCPDQ62proT7qiw6vA, fetchOffset=9596, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (7CMdqCPDQ62proT7qiw6vA:test-topic-0000044-0008-7,PartitionData(topicId=7CMdqCPDQ62proT7qiw6vA, fetchOffset=9782, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (7CMdqCPDQ62proT7qiw6vA:test-topic-0000044-0008-6,PartitionData(topicId=7CMdqCPDQ62proT7qiw6vA, fetchOffset=9061, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (7CMdqCPDQ62proT7qiw6vA:test-topic-0000044-0008-5,PartitionData(topicId=7CMdqCPDQ62proT7qiw6vA, fetchOffset=11315, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (7CMdqCPDQ62proT7qiw6vA:test-topic-0000044-0008-4,PartitionData(topicId=7CMdqCPDQ62proT7qiw6vA, fetchOffset=12130, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty))) since the wait time 500 exceed 500 ms. (kafka.server.ReplicaManager)
[2023-12-29 04:38:03,129] WARN [ReplicaManager broker=1] Returning emtpy fetch response for fetch request ArrayBuffer((PoiTbYJfQ6-3idLQUB_e5A:test-topic-0000038-0008-7,PartitionData(topicId=PoiTbYJfQ6-3idLQUB_e5A, fetchOffset=10392, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (PoiTbYJfQ6-3idLQUB_e5A:test-topic-0000038-0008-4,PartitionData(topicId=PoiTbYJfQ6-3idLQUB_e5A, fetchOffset=8936, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (PoiTbYJfQ6-3idLQUB_e5A:test-topic-0000038-0008-1,PartitionData(topicId=PoiTbYJfQ6-3idLQUB_e5A, fetchOffset=10027, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (PoiTbYJfQ6-3idLQUB_e5A:test-topic-0000038-0008-3,PartitionData(topicId=PoiTbYJfQ6-3idLQUB_e5A, fetchOffset=9983, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (PoiTbYJfQ6-3idLQUB_e5A:test-topic-0000038-0008-2,PartitionData(topicId=PoiTbYJfQ6-3idLQUB_e5A, fetchOffset=11817, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (PoiTbYJfQ6-3idLQUB_e5A:test-topic-0000038-0008-0,PartitionData(topicId=PoiTbYJfQ6-3idLQUB_e5A, fetchOffset=10375, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (PoiTbYJfQ6-3idLQUB_e5A:test-topic-0000038-0008-6,PartitionData(topicId=PoiTbYJfQ6-3idLQUB_e5A, fetchOffset=8998, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (PoiTbYJfQ6-3idLQUB_e5A:test-topic-0000038-0008-5,PartitionData(topicId=PoiTbYJfQ6-3idLQUB_e5A, fetchOffset=10315, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty))) since the wait time 500 exceed 500 ms. (kafka.server.ReplicaManager)
[2023-12-29 04:38:03,130] WARN [ReplicaManager broker=1] Returning emtpy fetch response for fetch request ArrayBuffer((BiSI-zKjQN2z9JAo-MVANg:test-topic-0000049-0008-5,PartitionData(topicId=BiSI-zKjQN2z9JAo-MVANg, fetchOffset=11114, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (BiSI-zKjQN2z9JAo-MVANg:test-topic-0000049-0008-2,PartitionData(topicId=BiSI-zKjQN2z9JAo-MVANg, fetchOffset=10513, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (BiSI-zKjQN2z9JAo-MVANg:test-topic-0000049-0008-7,PartitionData(topicId=BiSI-zKjQN2z9JAo-MVANg, fetchOffset=9984, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (BiSI-zKjQN2z9JAo-MVANg:test-topic-0000049-0008-6,PartitionData(topicId=BiSI-zKjQN2z9JAo-MVANg, fetchOffset=8817, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (BiSI-zKjQN2z9JAo-MVANg:test-topic-0000049-0008-3,PartitionData(topicId=BiSI-zKjQN2z9JAo-MVANg, fetchOffset=10861, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (BiSI-zKjQN2z9JAo-MVANg:test-topic-0000049-0008-4,PartitionData(topicId=BiSI-zKjQN2z9JAo-MVANg, fetchOffset=10344, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (BiSI-zKjQN2z9JAo-MVANg:test-topic-0000049-0008-1,PartitionData(topicId=BiSI-zKjQN2z9JAo-MVANg, fetchOffset=10167, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (BiSI-zKjQN2z9JAo-MVANg:test-topic-0000049-0008-0,PartitionData(topicId=BiSI-zKjQN2z9JAo-MVANg, fetchOffset=9052, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty))) since the wait time 500 exceed 500 ms. (kafka.server.ReplicaManager)
[2023-12-29 04:38:03,131] WARN [ReplicaManager broker=1] Returning emtpy fetch response for fetch request ArrayBuffer((ZXoBDmNgRp-tWsb3vR3Vjg:test-topic-0000048-0008-2,PartitionData(topicId=ZXoBDmNgRp-tWsb3vR3Vjg, fetchOffset=10590, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (ZXoBDmNgRp-tWsb3vR3Vjg:test-topic-0000048-0008-5,PartitionData(topicId=ZXoBDmNgRp-tWsb3vR3Vjg, fetchOffset=9086, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (ZXoBDmNgRp-tWsb3vR3Vjg:test-topic-0000048-0008-0,PartitionData(topicId=ZXoBDmNgRp-tWsb3vR3Vjg, fetchOffset=10102, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (ZXoBDmNgRp-tWsb3vR3Vjg:test-topic-0000048-0008-7,PartitionData(topicId=ZXoBDmNgRp-tWsb3vR3Vjg, fetchOffset=11083, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (ZXoBDmNgRp-tWsb3vR3Vjg:test-topic-0000048-0008-6,PartitionData(topicId=ZXoBDmNgRp-tWsb3vR3Vjg, fetchOffset=10811, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (ZXoBDmNgRp-tWsb3vR3Vjg:test-topic-0000048-0008-3,PartitionData(topicId=ZXoBDmNgRp-tWsb3vR3Vjg, fetchOffset=10305, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (ZXoBDmNgRp-tWsb3vR3Vjg:test-topic-0000048-0008-1,PartitionData(topicId=ZXoBDmNgRp-tWsb3vR3Vjg, fetchOffset=9768, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (ZXoBDmNgRp-tWsb3vR3Vjg:test-topic-0000048-0008-4,PartitionData(topicId=ZXoBDmNgRp-tWsb3vR3Vjg, fetchOffset=9049, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty))) since the wait time 500 exceed 500 ms. (kafka.server.ReplicaManager)
[2023-12-29 04:38:03,137] WARN [ReplicaManager broker=1] Returning emtpy fetch response for fetch request ArrayBuffer((RAER0854SYy1YUQQXxw6Vg:test-topic-0000039-0008-1,PartitionData(topicId=RAER0854SYy1YUQQXxw6Vg, fetchOffset=10556, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (RAER0854SYy1YUQQXxw6Vg:test-topic-0000039-0008-7,PartitionData(topicId=RAER0854SYy1YUQQXxw6Vg, fetchOffset=9907, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (RAER0854SYy1YUQQXxw6Vg:test-topic-0000039-0008-3,PartitionData(topicId=RAER0854SYy1YUQQXxw6Vg, fetchOffset=10030, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (RAER0854SYy1YUQQXxw6Vg:test-topic-0000039-0008-2,PartitionData(topicId=RAER0854SYy1YUQQXxw6Vg, fetchOffset=9827, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (RAER0854SYy1YUQQXxw6Vg:test-topic-0000039-0008-5,PartitionData(topicId=RAER0854SYy1YUQQXxw6Vg, fetchOffset=9888, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (RAER0854SYy1YUQQXxw6Vg:test-topic-0000039-0008-4,PartitionData(topicId=RAER0854SYy1YUQQXxw6Vg, fetchOffset=9897, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (RAER0854SYy1YUQQXxw6Vg:test-topic-0000039-0008-6,PartitionData(topicId=RAER0854SYy1YUQQXxw6Vg, fetchOffset=11202, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty)), (RAER0854SYy1YUQQXxw6Vg:test-topic-0000039-0008-0,PartitionData(topicId=RAER0854SYy1YUQQXxw6Vg, fetchOffset=9624, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[2], lastFetchedEpoch=Optional.empty))) since the wait time 505 exceed 500 ms. (kafka.server.ReplicaManager)
```

**Comment by Chillax-0v0** [comment]
part of #621
