### ISSUE TITLE
[BUG] stream read timeout

### ISSUE THREAD

**Issue by mooc9988** [AutoMQ/automq-for-kafka#680]
### Version & Environment

develop branch

### What went wrong?

```
024-01-15 21:15:04,992] INFO [FetchObjects],[PENDING],streamId=24 startOffset=1925 endOffset=7749 limit=2 (kafka.log.stream.s3.metadata.StreamMetadataManager)
[2024-01-15 21:15:05,334] ERROR read 24 [1830, 7749), maxBytes: 65536 from block cache fail (com.automq.stream.s3.cache.DefaultS3BlockCache)
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
        at java.base/java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2874)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.util.concurrent.TimeoutException
        ... 7 more
```

The failure leads to failure in opening stream in node 0.

StreamMetadataManager is always pending:
```
[2024-01-16 03:26:45,955] INFO [FetchObjects],[PENDING],streamId=24 startOffset=1925 endOffset=7749 limit=2 (kafka.log.stream.s3.metadata.StreamMetadataManager)
```

Arthas shows that the last offset in objects is 1934:
```
@InRangeObjects[
                INVALID=@InRangeObjects[InRangeObjects{streamId=-1, startOffset=-1, endOffset=-1, objects=[]}],
                streamId=@Long[24],
                startOffset=@Long[1925],
                endOffset=@Long[1934],
                objects=@LinkedList[isEmpty=false;size=1],
            ]
```

### How to reproduce the issue?

1.
2.
3.

### Additional information

Please attach any relevant logs, backtraces, or metric charts.

**Comment by mooc9988** [comment]
# What happened
* node 0 was trying to getObjects with streamId 24, range[1925, 7749).
* ranges for stream 24 are ...., [169, 186), [186, 1934), [1934, 2371),...
* [186, 1934) refers to stream set object; [169, 186) and [1934, 2371) refer to stream object;

getObjects first get stream set object[186, 1934), then hit :

![image](https://github.com/AutoMQ/automq-for-kafka/assets/26784194/a699bdee-3a86-47d8-b250-9e18a3149edb)
However, the range here is still stream object with range [169, 186). Objects are returned without stream object [1934, 2371).
