### ISSUE TITLE
[BUG] Compacted object is expired

### ISSUE THREAD

**Issue by superhx** [AutoMQ/automq-for-kafka#765]
43.192.128.117
```
[2024-02-03 00:49:57,680] ERROR [CompactionManager id=12] Commit force split request failed, ex:  (com.automq.stream.s3.compact.CompactionManager)
java.util.concurrent.CompletionException: org.apache.kafka.common.errors.s3.CompactedObjectsNotFoundException: The compacted objects are not found.
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
        at kafka.log.stream.s3.network.ControllerRequestSender$RequestTask.completeExceptionally(ControllerRequestSender.java:264)
        at kafka.log.stream.s3.network.ControllerRequestSender$1.onSuccess(ControllerRequestSender.java:91)
        at kafka.log.stream.s3.network.ControllerRequestSender$2.onComplete(ControllerRequestSender.java:129)
        at kafka.server.BrokerToControllerRequestThread.handleResponse(BrokerToControllerChannelManager.scala:413)
        at kafka.server.BrokerToControllerRequestThread.$anonfun$generateRequests$1(BrokerToControllerChannelManager.scala:376)
        at org.apache.kafka.clients.ClientResponse.onComplete(ClientResponse.java:109)
        at org.apache.kafka.clients.NetworkClient.completeResponses(NetworkClient.java:583)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:575)
        at kafka.common.InterBrokerSendThread.pollOnce(InterBrokerSendThread.scala:74)
        at kafka.server.BrokerToControllerRequestThread.doWork(BrokerToControllerChannelManager.scala:421)
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
Caused by: org.apache.kafka.common.errors.s3.CompactedObjectsNotFoundException: The compacted objects are not found.

[2024-02-03 01:24:23,982] ERROR [CompactionManager id=12] Commit compact request failed, ex:  (com.automq.stream.s3.compact.CompactionManager)
java.util.concurrent.CompletionException: org.apache.kafka.common.errors.s3.CompactedObjectsNotFoundException: The compacted objects are not found.
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
        at kafka.log.stream.s3.network.ControllerRequestSender$RequestTask.completeExceptionally(ControllerRequestSender.java:264)
        at kafka.log.stream.s3.network.ControllerRequestSender$1.onSuccess(ControllerRequestSender.java:91)
        at kafka.log.stream.s3.network.ControllerRequestSender$2.onComplete(ControllerRequestSender.java:129)
        at kafka.server.BrokerToControllerRequestThread.handleResponse(BrokerToControllerChannelManager.scala:413)
        at kafka.server.BrokerToControllerRequestThread.$anonfun$generateRequests$1(BrokerToControllerChannelManager.scala:376)
        at org.apache.kafka.clients.ClientResponse.onComplete(ClientResponse.java:109)
        at org.apache.kafka.clients.NetworkClient.completeResponses(NetworkClient.java:583)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:575)
        at kafka.common.InterBrokerSendThread.pollOnce(InterBrokerSendThread.scala:74)
        at kafka.server.BrokerToControllerRequestThread.doWork(BrokerToControllerChannelManager.scala:421)
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
Caused by: org.apache.kafka.common.errors.s3.CompactedObjectsNotFoundException: The compacted objects are not found.
```

**Comment by superhx** [comment]
```
grep 163328 controller.log.2024-02-03-00
[2024-02-03 00:06:46,781] INFO [Controller 0] [CommitStreamSetObject]: nodeId=11 commit object: 165429 success, compacted objects: [163328, 158848, 158849, 164609, 162699, 160651, 160015, 165260, 163980, 163724, 160397, 161299, 159249, 158998, 162327, 161812, 164888, 161567, 160927, 162978, 164259, 160807, 164516, 160808, 162094, 162606, 160559, 165167, 163631, 159666, 160305, 161718, 161206, 159158, 159412, 163514, 164795, 163257, 161465, 163910, 164166, 164423, 162885, 159945, 162258, 165074, 160467, 165331, 162513, 160721, 162001, 159574, 161114, 159066, 161883, 160856, 159321, 164702, 163164, 163421, 158949, 164330, 160235, 160107, 162792, 164073, 163817, 159853, 161650, 162163, 161393, 162420, 164981, 159482, 159736, 163071, 161020], stream range: [ObjectStreamRange(streamId=3, streamEpoch=0, startOffset=979, endOffset=1284), ObjectStreamRange(streamId=4, streamEpoch=0, startOffset=23650080, endOffset=23655130), ObjectStreamRange(streamId=6, streamEpoch=0, startOffset=22464, endOffset=30168), ObjectStreamRange(streamId=8, streamEpoch=0, startOffset=1013, endOffset=1019), ObjectStreamRange(streamId=16, streamEpoch=0, startOffset=1438, endOffset=1745), ObjectStreamRange(streamId=19, streamEpoch=0, startOffset=18440250, endOffset=18442700), ObjectStreamRange(streamId=22, streamEpoch=0, startOffset=940, endOffset=1243), ObjectStreamRange(streamId=24, streamEpoch=0, startOffset=1449, endOffset=1756), ObjectStreamRange(streamId=29, streamEpoch=0, startOffset=1487, endOffset=1493), ObjectStreamRange(streamId=32, streamEpoch=0, startOffset=974, endOffset=1278), ObjectStreamRange(streamId=33, streamEpoch=0, startOffset=1393, endOffset=1399), ObjectStreamRange(streamId=37, streamEpoch=0, startOffset=1733, endOffset=1739), ObjectStreamRange(streamId=39, streamEpoch=0, startOffset=1231, endOffset=1237), ObjectStreamRange(streamId=40, streamEpoch=0, startOffset=1288, endOffset=1294), ObjectStreamRange(streamId=45, streamEpoch=0, startOffset=22524, endOffset=22860), ObjectStreamRange(streamId=50, streamEpoch=0, startOffset=1747, endOffset=1805), ObjectStreamRange(streamId=53, streamEpoch=0, startOffset=1348, endOffset=1653), ObjectStreamRange(streamId=55, streamEpoch=0, startOffset=1635, endOffset=1693), ObjectStreamRange(streamId=58, streamEpoch=0, startOffset=32202413, endOffset=32208771), ObjectStreamRange(streamId=60, streamEpoch=0, startOffset=1267, endOffset=1273), ObjectStreamRange(streamId=61, streamEpoch=0, startOffset=1263, endOffset=1271), ObjectStreamRange(streamId=67, streamEpoch=0, startOffset=1065, endOffset=1370), ObjectStreamRange(streamId=70, streamEpoch=0, startOffset=32202549, endOffset=32208388), ObjectStreamRange(streamId=71, streamEpoch=0, startOffset=26960375, endOffset=26962515), ObjectStreamRange(streamId=72, streamEpoch=0, startOffset=23636616, endOffset=23643072), ObjectStreamRange(streamId=76, streamEpoch=0, startOffset=1202, endOffset=1208), ObjectStreamRange(streamId=78, streamEpoch=0, startOffset=26926768, endOffset=26928927), ObjectStreamRange(streamId=86, streamEpoch=0, startOffset=23630448, endOffset=23636055), ObjectStreamRange(streamId=87, streamEpoch=0, startOffset=23658063, endOffset=23664182), ObjectStreamRange(streamId=89, streamEpoch=0, startOffset=1009, endOffset=1015), ObjectStreamRange(streamId=90, streamEpoch=0, startOffset=1072, endOffset=1381), ObjectStreamRange(streamId=91, streamEpoch=0, startOffset=1348, endOffset=1655), ObjectStreamRange(streamId=95, streamEpoch=0, startOffset=23644197, endOffset=23651427), ObjectStreamRange(streamId=98, streamEpoch=0, startOffset=32952, endOffset=40608), ObjectStreamRange(streamId=101, streamEpoch=0, startOffset=32128854, endOffset=32136599), ObjectStreamRange(streamId=102, streamEpoch=0, startOffset=1684, endOffset=1690), ObjectStreamRange(streamId=103, streamEpoch=0, startOffset=1715, endOffset=1721), ObjectStreamRange(streamId=106, streamEpoch=0, startOffset=32192061, endOffset=32198970), ObjectStreamRange(streamId=113, streamEpoch=0, startOffset=32928, endOffset=39324), ObjectStreamRange(streamId=114, streamEpoch=0, startOffset=32856, endOffset=33192), ObjectStreamRange(streamId=115, streamEpoch=0, startOffset=22536, endOffset=30180), ObjectStreamRange(streamId=122, streamEpoch=0, startOffset=32928, endOffset=33240), ObjectStreamRange(streamId=124, streamEpoch=0, startOffset=32136877, endOffset=32142897), ObjectStreamRange(streamId=126, streamEpoch=0, startOffset=23764164, endOffset=23770464), ObjectStreamRange(streamId=128, streamEpoch=0, startOffset=23665119, endOffset=23670229), ObjectStreamRange(streamId=129, streamEpoch=0, startOffset=32145506, endOffset=32152984), ObjectStreamRange(streamId=133, streamEpoch=0, startOffset=22476, endOffset=28848), ObjectStreamRange(streamId=134, streamEpoch=0, startOffset=22452, endOffset=28872), ObjectStreamRange(streamId=138, streamEpoch=0, startOffset=31857900, endOffset=31865178), ObjectStreamRange(streamId=139, streamEpoch=0, startOffset=18427872, endOffset=18431096), ObjectStreamRange(streamId=141, streamEpoch=0, startOffset=22488, endOffset=30180), ObjectStreamRange(streamId=143, streamEpoch=0, startOffset=32202843, endOffset=32209711), ObjectStreamRange(streamId=145, streamEpoch=0, startOffset=1230, endOffset=1290), ObjectStreamRange(streamId=148, streamEpoch=0, startOffset=18443830, endOffset=18444770), ObjectStreamRange(streamId=149, streamEpoch=0, startOffset=23646857, endOffset=23653494), ObjectStreamRange(streamId=155, streamEpoch=0, startOffset=32868, endOffset=40476), ObjectStreamRange(streamId=158, streamEpoch=0, startOffset=38928, endOffset=40644), ObjectStreamRange(streamId=164, streamEpoch=0, startOffset=1244, endOffset=1302), ObjectStreamRange(streamId=165, streamEpoch=0, startOffset=38832, endOffset=40512), ObjectStreamRange(streamId=172, streamEpoch=0, startOffset=28992, endOffset=29184), ObjectStreamRange(streamId=174, streamEpoch=0, startOffset=28500, endOffset=28908), ObjectStreamRange(streamId=175, streamEpoch=0, startOffset=32928, endOffset=40704), ObjectStreamRange(streamId=177, streamEpoch=0, startOffset=1512, endOffset=1805), ObjectStreamRange(streamId=180, streamEpoch=0, startOffset=32191067, endOffset=32195487), ObjectStreamRange(streamId=181, streamEpoch=0, startOffset=23602954, endOffset=23609920), ObjectStreamRange(streamId=187, streamEpoch=0, startOffset=23615099, endOffset=23621362), ObjectStreamRange(streamId=195, streamEpoch=0, startOffset=1027, endOffset=1338), ObjectStreamRange(streamId=196, streamEpoch=0, startOffset=1074, endOffset=1373), ObjectStreamRange(streamId=198, streamEpoch=0, startOffset=964, endOffset=970), ObjectStreamRange(streamId=199, streamEpoch=0, startOffset=32178238, endOffset=32185015), ObjectStreamRange(streamId=200, streamEpoch=0, startOffset=38820, endOffset=38832), ObjectStreamRange(streamId=201, streamEpoch=0, startOffset=22464, endOffset=28440), ObjectStreamRange(streamId=202, streamEpoch=0, startOffset=32892, endOffset=40680), ObjectStreamRange(streamId=204, streamEpoch=0, startOffset=1263, endOffset=1269), ObjectStreamRange(streamId=205, streamEpoch=0, startOffset=1304, endOffset=1362), ObjectStreamRange(streamId=208, streamEpoch=0, startOffset=1475, endOffset=1481), ObjectStreamRange(streamId=215, streamEpoch=0, startOffset=1279, endOffset=1285), ObjectStreamRange(streamId=216, streamEpoch=0, startOffset=23658601, endOffset=23664174), ObjectStreamRange(streamId=217, streamEpoch=0, startOffset=22548, endOffset=22656), ObjectStreamRange(streamId=218, streamEpoch=0, startOffset=22536, endOffset=30216), ObjectStreamRange(streamId=224, streamEpoch=0, startOffset=1216, endOffset=1288), ObjectStreamRange(streamId=225, streamEpoch=0, startOffset=1001, endOffset=1306), ObjectStreamRange(streamId=228, streamEpoch=0, startOffset=1258, endOffset=1264), ObjectStreamRange(streamId=232, streamEpoch=0, startOffset=22524, endOffset=30192), ObjectStreamRange(streamId=233, streamEpoch=0, startOffset=22452, endOffset=28812), ObjectStreamRange(streamId=235, streamEpoch=0, startOffset=1041, endOffset=1345), ObjectStreamRange(streamId=245, streamEpoch=0, startOffset=23321983, endOffset=23328796), ObjectStreamRange(streamId=248, streamEpoch=0, startOffset=1029, endOffset=1337), ObjectStreamRange(streamId=252, streamEpoch=0, startOffset=32892, endOffset=39276), ObjectStreamRange(streamId=256, streamEpoch=0, startOffset=28500, endOffset=30276), ObjectStreamRange(streamId=258, streamEpoch=0, startOffset=1324, endOffset=1631), ObjectStreamRange(streamId=259, streamEpoch=0, startOffset=1620, endOffset=1678), ObjectStreamRange(streamId=261, streamEpoch=0, startOffset=18435341, endOffset=18437841), ObjectStreamRange(streamId=262, streamEpoch=0, startOffset=23640392, endOffset=23644985), ObjectStreamRange(streamId=263, streamEpoch=0, startOffset=38964, endOffset=39276), ObjectStreamRange(streamId=267, streamEpoch=0, startOffset=32166084, endOffset=32172489), ObjectStreamRange(streamId=269, streamEpoch=0, startOffset=23632050, endOffset=23637353), ObjectStreamRange(streamId=270, streamEpoch=0, startOffset=23591607, endOffset=23598789), ObjectStreamRange(streamId=272, streamEpoch=0, startOffset=23632033, endOffset=23638236), ObjectStreamRange(streamId=277, streamEpoch=0, startOffset=28476, endOffset=28488), ObjectStreamRange(streamId=283, streamEpoch=0, startOffset=31873742, endOffset=31881334), ObjectStreamRange(streamId=284, streamEpoch=0, startOffset=23611082, endOffset=23618209), ObjectStreamRange(streamId=285, streamEpoch=0, startOffset=22512, endOffset=22812), ObjectStreamRange(streamId=286, streamEpoch=0, startOffset=23622539, endOffset=23629614), ObjectStreamRange(streamId=291, streamEpoch=0, startOffset=22512, endOffset=28860), ObjectStreamRange(streamId=292, streamEpoch=0, startOffset=22500, endOffset=30168), ObjectStreamRange(streamId=293, streamEpoch=0, startOffset=22728, endOffset=30180), ObjectStreamRange(streamId=301, streamEpoch=0, startOffset=26952589, endOffset=26955375), ObjectStreamRange(streamId=302, streamEpoch=0, startOffset=23641198, endOffset=23646697), ObjectStreamRange(streamId=304, streamEpoch=0, startOffset=23684348, endOffset=23690521), ObjectStreamRange(streamId=311, streamEpoch=0, startOffset=32199566, endOffset=32207040), ObjectStreamRange(streamId=312, streamEpoch=0, startOffset=32281300, endOffset=32287126), ObjectStreamRange(streamId=317, streamEpoch=0, startOffset=38904, endOffset=38916), ObjectStreamRange(streamId=318, streamEpoch=0, startOffset=22512, endOffset=30132), ObjectStreamRange(streamId=320, streamEpoch=0, startOffset=22512, endOffset=30228), ObjectStreamRange(streamId=323, streamEpoch=0, startOffset=23637607, endOffset=23644956), ObjectStreamRange(streamId=326, streamEpoch=0, startOffset=23684595, endOffset=23688120), ObjectStreamRange(streamId=328, streamEpoch=0, startOffset=23610629, endOffset=23615563), ObjectStreamRange(streamId=330, streamEpoch=0, startOffset=31849005, endOffset=31856034), ObjectStreamRange(streamId=331, streamEpoch=0, startOffset=28488, endOffset=30276), ObjectStreamRange(streamId=333, streamEpoch=0, startOffset=33348, endOffset=40608), ObjectStreamRange(streamId=337, streamEpoch=0, startOffset=38844, endOffset=40572), ObjectStreamRange(streamId=338, streamEpoch=0, startOffset=32928, endOffset=40668), ObjectStreamRange(streamId=361, streamEpoch=0, startOffset=32880, endOffset=33192), ObjectStreamRange(streamId=363, streamEpoch=0, startOffset=22488, endOffset=28872), ObjectStreamRange(streamId=365, streamEpoch=0, startOffset=28476, endOffset=30204), ObjectStreamRange(streamId=385, streamEpoch=0, startOffset=22500, endOffset=30264), ObjectStreamRange(streamId=388, streamEpoch=0, startOffset=22500, endOffset=28920), ObjectStreamRange(streamId=390, streamEpoch=0, startOffset=28440, endOffset=30132), ObjectStreamRange(streamId=392, streamEpoch=0, startOffset=38820, endOffset=38832)], stream objects: [StreamObject(objectId=165400, objectSize=2040266, streamId=4, startOffset=18415906, endOffset=18417871), StreamObject(objectId=165401, objectSize=1748874, streamId=4, startOffset=23330631, endOffset=23332273), StreamObject(objectId=165402, objectSize=3236238, streamId=58, startOffset=26995376, endOffset=26998489), StreamObject(objectId=165403, objectSize=2741440, streamId=58, startOffset=31897098, endOffset=31899656), StreamObject(objectId=165404, objectSize=2536120, streamId=70, startOffset=26949884, endOffset=26952324), StreamObject(objectId=165405, objectSize=4428984, streamId=70, startOffset=31879701, endOffset=31883851), StreamObject(objectId=165406, objectSize=2053823, streamId=72, startOffset=18428821, endOffset=18430797), StreamObject(objectId=165407, objectSize=1881538, streamId=72, startOffset=23317515, endOffset=23319265), StreamObject(objectId=165408, objectSize=2186460, streamId=86, startOffset=18413203, endOffset=18415309), StreamObject(objectId=165409, objectSize=2287419, streamId=86, startOffset=23320940, endOffset=23323077), StreamObject(objectId=165410, objectSize=3052243, streamId=87, startOffset=18402420, endOffset=18405358), StreamObject(objectId=165411, objectSize=3085939, streamId=87, startOffset=23330996, endOffset=23333877), StreamObject(objectId=165412, objectSize=3150026, streamId=95, startOffset=18416945, endOffset=18419980), StreamObject(objectId=165413, objectSize=1613646, streamId=95, startOffset=23334903, endOffset=23336411), StreamObject(objectId=165414, objectSize=3111098, streamId=101, startOffset=26961767, endOffset=26964761), StreamObject(objectId=165415, objectSize=2290046, streamId=101, startOffset=31829651, endOffset=31831793), StreamObject(objectId=165416, objectSize=7149410, streamId=106, startOffset=31879406, endOffset=31886080), StreamObject(objectId=165417, objectSize=1842668, streamId=124, startOffset=26947298, endOffset=26949070), StreamObject(objectId=165418, objectSize=3753748, streamId=124, startOffset=31856379, endOffset=31859917), StreamObject(objectId=165419, objectSize=5632761, streamId=128, startOffset=23339496, endOffset=23344755), StreamObject(objectId=165420, objectSize=2727350, streamId=129, startOffset=26942879, endOffset=26945504), StreamObject(objectId=165421, objectSize=3282174, streamId=129, startOffset=31840134, endOffset=31843213), StreamObject(objectId=165422, objectSize=1553948, streamId=143, startOffset=26966988, endOffset=26968486), StreamObject(objectId=165423, objectSize=1251663, streamId=143, startOffset=31885433, endOffset=31886600), StreamObject(objectId=165424, objectSize=2621897, streamId=149, startOffset=18423341, endOffset=18425864), StreamObject(objectId=165425, objectSize=2564359, streamId=149, startOffset=23337742, endOffset=23340145), StreamObject(objectId=165426, objectSize=549, streamId=165, startOffset=32832, endOffset=32940), StreamObject(objectId=165427, objectSize=1702644, streamId=180, startOffset=26953993, endOffset=26955630), StreamObject(objectId=165428, objectSize=2816010, streamId=180, startOffset=31865898, endOffset=31868522), StreamObject(objectId=171020, objectSize=3153750, streamId=181, startOffset=18403598, endOffset=18406633), StreamObject(objectId=171021, objectSize=1795838, streamId=181, startOffset=23280420, endOffset=23282096), StreamObject(objectId=171022, objectSize=2719588, streamId=187, startOffset=18407277, endOffset=18409895), StreamObject(objectId=171023, objectSize=2381938, streamId=187, startOffset=23305042, endOffset=23307270), StreamObject(objectId=171024, objectSize=4445979, streamId=199, startOffset=31924866, endOffset=31929061), StreamObject(objectId=171025, objectSize=6987682, streamId=216, startOffset=23355022, endOffset=23361544), StreamObject(objectId=171026, objectSize=6338860, streamId=262, startOffset=23328064, endOffset=23333978), StreamObject(objectId=171027, objectSize=2299256, streamId=267, startOffset=31857473, endOffset=31859617), StreamObject(objectId=171028, objectSize=1611087, streamId=269, startOffset=18428524, endOffset=18430073), StreamObject(objectId=171029, objectSize=2186656, streamId=269, startOffset=23317922, endOffset=23319960), StreamObject(objectId=171030, objectSize=2596570, streamId=270, startOffset=18401964, endOffset=18404463), StreamObject(objectId=171031, objectSize=3306602, streamId=270, startOffset=23286391, endOffset=23289479), StreamObject(objectId=171032, objectSize=2480067, streamId=272, startOffset=18426673, endOffset=18429060), StreamObject(objectId=171033, objectSize=3065342, streamId=272, startOffset=23314476, endOffset=23317351), StreamObject(objectId=171034, objectSize=3432893, streamId=284, startOffset=18421485, endOffset=18424792), StreamObject(objectId=171035, objectSize=2529869, streamId=284, startOffset=23296938, endOffset=23299308), StreamObject(objectId=171036, objectSize=2905502, streamId=286, startOffset=18408032, endOffset=18410829), StreamObject(objectId=171037, objectSize=2838162, streamId=286, startOffset=23313068, endOffset=23315724), StreamObject(objectId=171038, objectSize=3106160, streamId=302, startOffset=18407711, endOffset=18410701), StreamObject(objectId=171039, objectSize=2025026, streamId=302, startOffset=23332825, endOffset=23334719), StreamObject(objectId=171040, objectSize=7962515, streamId=304, startOffset=23343372, endOffset=23350593), StreamObject(objectId=171041, objectSize=2156033, streamId=304, startOffset=23377589, endOffset=23379608), StreamObject(objectId=171042, objectSize=6883661, streamId=311, startOffset=31858985, endOffset=31865236), StreamObject(objectId=171043, objectSize=1614216, streamId=311, startOffset=31891423, endOffset=31892925), StreamObject(objectId=171044, objectSize=3076572, streamId=312, startOffset=27023697, endOffset=27026659), StreamObject(objectId=171045, objectSize=2013758, streamId=312, startOffset=31967352, endOffset=31969234), StreamObject(objectId=171603, objectSize=2252576, streamId=323, startOffset=18408582, endOffset=18410753), StreamObject(objectId=171604, objectSize=3378350, streamId=323, startOffset=23324703, endOffset=23327859), StreamObject(objectId=171605, objectSize=1737387, streamId=326, startOffset=18422181, endOffset=18423853), StreamObject(objectId=171606, objectSize=2542996, streamId=326, startOffset=23369159, endOffset=23371539), StreamObject(objectId=171607, objectSize=6456018, streamId=328, startOffset=23302516, endOffset=23308532)] (org.apache.kafka.controller.stream.StreamControlManager)
[2024-02-03 00:16:44,651] ERROR [Controller 0] object 163328 not exist when mark destroy object (org.apache.kafka.controller.stream.S3ObjectControlManager)
[2024-02-03 00:16:44,651] ERROR [Controller 0] [CommitStreamSetObject]: Mark destroy compacted objects: [163328, 164609, 168714, 167434, 165640, 167177, 160015, 168972, 170252, 161299, 159249, 158998, 162327, 161812, 164888, 165919, 161567, 170531, 169251, 166432, 167713, 160807, 170788, 169508, 160808, 162094, 162606, 160559, 165167, 163631, 160305, 166198, 166711, 169787, 167992, 171328, 163910, 164166, 164423, 162885, 165454, 166991, 168271, 170066, 168528, 159574, 161114, 159066, 161883, 160856, 159321, 164702, 163164, 163421, 167270, 167527, 168807, 165733, 160107, 170345, 169065, 159853, 161650, 162163, 171632, 161393, 162420, 164981, 167806, 166012, 166525, 170624, 169344, 158848, 169601, 158849, 170881, 162699, 160651, 165260, 163980, 163724, 160397, 166291, 168342, 166805, 168085, 169880, 160927, 162978, 164259, 164516, 165547, 170159, 168879, 167084, 168621, 159666, 171443, 161718, 161206, 159158, 159412, 163514, 164795, 163257, 161465, 165826, 167363, 166339, 170438, 169158, 167620, 159945, 162258, 165074, 160467, 165331, 162513, 160721, 162001, 166618, 167899, 166105, 170974, 169694, 170717, 169437, 171235, 158949, 164330, 160235, 162792, 164073, 163817, 168178, 166898, 168435, 169973, 159482, 159736, 163071, 161020] failed (org.apache.kafka.controller.stream.StreamControlManager)
```

**Comment by superhx** [comment]
fixed in https://github.com/AutoMQ/automq-for-rocketmq/pull/918
